In [1]:
#Import Beautiful Soup
from bs4 import BeautifulSoup

web='''
    <html>
        <h1>Heading 1.1</h1>
        <h1>Heading 1.2</h1>
        <h1>Heading 1.3</h1>
        <h1>Heading 1.4</h1>
        <h2 class='C1' id='Head1'>Heading 2.1</h2>
        <h2 class='C1'>Heading 2.2</h2>
        <h2 class='C2'>Heading 2.3</h2>
        <h2 class='C2'>Heading 2.4</h2>
        <p class='P1'>Hewllo World</p>
        <p>Python World</p>
        <p class='P1'>AI World</p>
    </html>
    '''

#Initialize the object with a HTML page
soup=BeautifulSoup(web,'html.parser')
print(web.upper())  #web=>has string formate.
print(soup.prettify())
print(soup)  #has html code.

    <HTML>
        <H1>HEADING 1.1</H1>
        <H1>HEADING 1.2</H1>
        <H1>HEADING 1.3</H1>
        <H1>HEADING 1.4</H1>
        <H2 CLASS='C1' ID='HEAD1'>HEADING 2.1</H2>
        <H2 CLASS='C1'>HEADING 2.2</H2>
        <H2 CLASS='C2'>HEADING 2.3</H2>
        <H2 CLASS='C2'>HEADING 2.4</H2>
        <P CLASS='P1'>HEWLLO WORLD</P>
        <P>PYTHON WORLD</P>
        <P CLASS='P1'>AI WORLD</P>
    </HTML>

<html>
 <h1>
  Heading 1.1
 </h1>
 <h1>
  Heading 1.2
 </h1>
 <h1>
  Heading 1.3
 </h1>
 <h1>
  Heading 1.4
 </h1>
 <h2 class="C1" id="Head1">
  Heading 2.1
 </h2>
 <h2 class="C1">
  Heading 2.2
 </h2>
 <h2 class="C2">
  Heading 2.3
 </h2>
 <h2 class="C2">
  Heading 2.4
 </h2>
 <p class="P1">
  Hewllo World
 </p>
 <p>
  Python World
 </p>
 <p class="P1">
  AI World
 </p>
</html>


<html>
<h1>Heading 1.1</h1>
<h1>Heading 1.2</h1>
<h1>Heading 1.3</h1>
<h1>Heading 1.4</h1>
<h2 class="C1" id="Head1">Heading 2.1</h2>
<h2 class="C1">Heading 2.2</h2>
<h2 class="C2">Heading 2.3</h2>
<h2 class="C2">Heading 2.4</h2>
<p class="P1">Hewllo World</p>
<p>Python World</p>
<p class="P1">AI World</p>
</html>

In [23]:
header2=soup.find('h2')
header2

In [25]:
header2=soup.find('h2',{'class':'C1'})
header2

In [27]:
header2=soup.find('h2',string='Heading 2.4')
header2

In [29]:
# header2=soup.find('h2',string='Heading 2.4 ')
# header2  #write as it is

In [31]:
header2.name

'h2'

In [33]:
header2.attrs

{'class': ['C2']}

In [35]:
header2.get('id','Not present') #jo id hase to id nu name aapse jo nahi hoi to not present print thase

'Not present'

In [57]:
header2.get('class','Not present')

['C2']

In [39]:
header2.get('href','Not present')

'Not present'

In [41]:
header2['class'] #2nd method to find the class name

['C2']

In [59]:
header2['id']

KeyError: 'id'

In [45]:
header2.text

'Heading 2.4'

In [47]:
header2.text[::-1].upper()

'4.2 GNIDAEH'

In [49]:
header2.get_text(strip=True) #extra spaces nikadi de.ex:'  Heading 2.4  ' => 'Heading 2.4'

'Heading 2.4'

In [51]:
soup.get_text(separator='_|_',strip=True)

'Heading 1.1_|_Heading 1.2_|_Heading 1.3_|_Heading 1.4_|_Heading 2.1_|_Heading 2.2_|_Heading 2.3_|_Heading 2.4_|_Hewllo World_|_Python World_|_AI World'

In [53]:
header3=soup.find_all('h2')
header3

[<h2 class="C1" id="Head1">Heading 2.1</h2>,
 <h2 class="C1">Heading 2.2</h2>,
 <h2 class="C2">Heading 2.3</h2>,
 <h2 class="C2">Heading 2.4</h2>]

In [55]:
header3.text

AttributeError: ResultSet object has no attribute 'text'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

In [19]:
for i in header3:
    print(i.text)

Heading 2.1
Heading 2.2
Heading 2.3
Heading 2.4

In [21]:
header3=soup.find_all('h2',attrs={'class':'C1'})
for i in header3:
    print(i.attrs)

{'class': ['C1'], 'id': 'Head1'}
{'class': ['C1']}

In [23]:
header3=soup.find_all('h2',limit=4)
for i in header3:
    print(i.attrs)

{'class': ['C1'], 'id': 'Head1'}
{'class': ['C1']}
{'class': ['C2']}
{'class': ['C2']}

# TrumpLies

In [15]:
import bs4
import pandas as pd
fh=open('TrumpLies.html',encoding='utf8')
soup=bs4.BeautifulSoup(fh,'html.parser')
# print(soup.prettify())

In [16]:
#print text of title tag
soup.title.text

'\n   Opinion | President Trump’s Lies, the Definitive List - The New York Times\n  '

In [17]:
soup.title.text.strip().split()[0]

'Opinion'

In [18]:
#print text of footer tag
soup.center.text

'\n\nKeep Calm and Write the Code😊August 15, 1947\n  '

In [19]:
soup.center.text.strip().split('😊')[-1]

'August 15, 1947'

In [20]:
#print text of all h1 tags
h1=soup.find_all('h1')
for i in h1:
    print(i.text)

         President Trump’s Lies, the Definitive List



         T


         r


         u


         m


         p


         ’


         s




         L


         i


         e


         s

In [21]:
#extract the text of p tag having class name 'secret-word'
secret=soup.find('p',{'class':'secret-word'})# only check secret
secret.text

'blackpink'

In [22]:
#print the text which have length more then 5 or 5 of first para. 
p=soup.find('p',{'class':'g-body'}).text.strip().split()
for i in p:
    if len(i)>4:
        print(i)

Americans
become
accustomed
President
Trump’s
lies.
regular
become,
country
should
allow
itself
become
them.
catalogued
nearly
every
outright
publicly
since
taking
office.
Updated
president
still
lying,
we've
added
list,
taking
through
provided
links
facts
case.

In [23]:
#print the word 'UPDATED' from 1st para.
s=soup.find('strong').text.strip()
s

'Updated'

In [24]:
date=[]
stat=[]
tt=[]

for tag in soup.find_all('span',{'class':'short-desc'}):
    d=tag.strong.text.strip()
    date.append(d)
print(date)

['Jan. 21', 'Jan. 21', 'Jan. 23', 'Jan. 25', 'Jan. 25', 'Jan. 25', 'Jan. 25', 'Jan. 26', 'Jan. 26', 'Jan. 28', 'Jan. 29', 'Jan. 30', 'Feb. 3', 'Feb. 4', 'Feb. 5', 'Feb. 6', 'Feb. 6', 'Feb. 6', 'Feb. 6', 'Feb. 7', 'Feb. 7', 'Feb. 9', 'Feb. 9', 'Feb. 10', 'Feb. 12', 'Feb. 16', 'Feb. 16', 'Feb. 16', 'Feb. 16', 'Feb. 16', 'Feb. 16', 'Feb. 18', 'Feb. 18', 'Feb. 24', 'Feb. 24', 'Feb. 24', 'Feb. 27', 'Feb. 27', 'Feb. 28', 'Feb. 28', 'Feb. 28', 'March 3', 'March 4', 'March 4', 'March 7', 'March 13', 'March 13', 'March 15', 'March 17', 'March 20', 'March 21', 'March 22', 'March 22', 'March 22', 'March 29', 'March 31', 'April 2', 'April 2', 'April 5', 'April 6', 'April 11', 'April 12', 'April 12', 'April 12', 'April 12', 'April 16', 'April 18', 'April 21', 'April 21', 'April 27', 'April 28', 'April 28', 'April 28', 'April 29', 'April 29', 'April 29', 'April 29', 'April 29', 'April 29', 'May 1', 'May 1', 'May 1', 'May 2', 'May 4', 'May 4', 'May 4', 'May 8', 'May 8', 'May 8', 'May 12', 'May 12', 'May 13', 'May 26', 'June 1', 'June 1', 'June 4', 'June 5', 'June 20', 'June 21', 'June 21', 'June 21', 'June 21', 'June 21', 'June 21', 'June 21', 'June 21', 'June 22', 'June 23', 'June 27', 'June 28', 'June 29', 'July 6', 'July 17', 'July 19', 'July 19', 'July 19', 'July 19', 'July 24', 'July 25', 'July 25', 'July 25', 'July 25', 'July 28', 'July 28', 'July 31', 'July 31', 'Aug. 1', 'Aug. 3', 'Aug. 3', 'Aug. 3', 'Aug. 15', 'Aug. 22', 'Aug. 22', 'Aug. 22', 'Aug. 22', 'Aug. 22', 'Sept. 6', 'Sept. 6', 'Sept. 8', 'Sept. 14', 'Sept. 14', 'Sept. 22', 'Sept. 22', 'Sept. 29', 'Sept. 27', 'Sept. 27', 'Sept. 27', 'Sept. 27', 'Sept. 28', 'Oct. 3', 'Oct. 3', 'Oct. 6', 'Oct. 6', 'Oct. 6', 'Oct. 6', 'Oct. 7', 'Oct. 7', 'Oct. 7', 'Oct. 10', 'Oct. 10', 'Oct. 11', 'Oct. 16', 'Oct. 16', 'Oct. 16', 'Oct. 16', 'Oct. 17', 'Oct. 17', 'Oct. 17', 'Oct. 17', 'Oct. 17', 'Oct. 17', 'Oct. 18', 'Oct. 18', 'Oct. 18', 'Oct. 24', 'Oct. 25', 'Oct. 27', 'Nov. 1', 'Nov. 7', 'Nov. 11']

In [25]:
for tag in soup.find_all('span',{'class':'short-truth'}):
    d=tag.text.strip()
    tt.append(d[1:-1])
print(tt)

['He was for an invasion before he was against it.', 'Trump was on the cover 11 times and Nixon appeared 55 times.', "There's no evidence of illegal voting.", "Official aerial photos show Obama's 2009 inauguration was much more heavily attended.", 'The report never mentioned voter fraud.', 'The real number is less than 1 million, according to the Urban Institute.', 'There were no gun homicide victims in Chicago that day.', 'Vetting lasts up to two years.', 'Most of the cuts were already planned.', 'It never apologized.', 'There is no support for this.', 'At least 746 people were detained and processed, and the Delta outage happened two days later.', 'There is no evidence of paid protesters.', 'It never apologized.', 'About 60,000 people were affected.', 'Much of the price drop was projected before Trump took office.', 'Terrorism has been reported on, often in detail.', "It didn't apologize.", 'The group’s origins date to 2004.', "It was higher in the 1980s and '90s.", 'The Defense Department projected this price drop before Trump took office.', "It was part of Cuomo's first question.", 'The Gorsuch comments were later corroborated.', "Trump knew about Flynn's actions for weeks.", 'The media did cover it.', 'George H.W. Bush, Bill Clinton and Barack Obama all won bigger margins in the Electoral College.', "Delta's problems happened two days later.", 'The jobs are a result of its investment plans announced in Oct. 2016.', 'Not always. They have released classified information in the past.', 'The rollout was chaotic.', 'It was widely covered.', 'Refugees receive multiple background checks, taking up to two years.', 'Trump implied there was a terror attack in Sweden, but there was no such attack.', 'There was no evidence of long lines.', 'Only its union did.', 'Obamacare increased coverage by a net of about 20 million.', 'Many fewer pulled out.', 'Much of the price cut was already projected.', 'NATO countries agreed to meet defense spending requirements in 2014.', "There's no evidence that the Waters of the United States rule caused severe job losses.", "They can't lobby their former agency but can still become lobbyists.", 'Paperwork for the last two candidates was still not submitted to the Senate.', "There's no evidence of a wiretap.", "There's no evidence of a wiretap.", '113 of them were released by President George W. Bush.', 'Much of the cost cuts were planned before Trump.', 'About 20 million people gained insurance under Obamacare.', 'Much of the cost cuts were planned before Trump.', "There's at least one insurer in every Tennessee county.", 'Much of the cost cuts were planned before Trump.', 'Much of the cost cuts were planned before Trump.', 'Riots in Sweden broke out two days later and there were no deaths.', 'It has fought terrorism since the 1980s.', "There's no evidence of widespread voter fraud.", "It didn't apologize.", 'These investments were already planned.', 'He was for an invasion before he was against it.', 'There is still no evidence.', 'Every marketplace region in Tennessee had at least one insurer.', 'Much of the price cuts were already projected.', 'He knew Steve Bannon since 2011.', 'At this point, he had not nominated anyone for hundreds of positions.', 'There were separate headlines for print and web, but neither were altered.', 'NATO has been engaged in counterterrorism efforts since the 1980s.', 'The campaign was expected to take months.', "There's no evidence of paid protesters.", 'He did.', 'Much of the price cuts were already projected.', 'He criticized it as early as 2010.', 'The bill to extend health benefits for certain coal miners was introduced by a Democrat and was co-sponsored by mostly Democrats.', 'The U.S. had an $8.1 billion trade surplus, not deficit, with Canada in 2016.', "Those are not Jon Ossoff's positions.", 'Much of the price cuts were planned before Trump.', 'China stopped years ago.', 'Much of the price cuts were planned before Trump.', 'The deal was struck in 2014.', 'China stopped in 2014.', 'Most of the cuts were planned before Trump.', "There's still no evidence Trump's phones were tapped.", 'The bill weakens protections for people with pre-existing conditions.', 'Much of the price cuts were planned before Trump.', 'China stopped years ago.', 'Much of the cost cuts were planned before Trump.', 'China stopped years ago.', "We're not.", 'Polls show most Americans do care.', 'The deal was struck in 2014.', "Colbert's Late Show debut had nearly two million more viewers.", "Clapper only said he wasn't aware of an investigation.", 'The F.B.I. was investigating before the election.', "Clapper said he wouldn't have been told of an investigation into collusion.", 'The cost cuts were planned before he became president.', "He's referencing an arms deal that's not enacted and other apparent deals that weren't announced on the trip.", 'The agreement doesn’t allow or disallow building coal plants.', 'Trump’s figures are inflated and premature.', 'The mayor was specifically talking about the enlarged police presence on the streets.', 'Trump signed this version of the travel ban, not the Justice Department.', 'Republicans have won four special elections this year, while a Democrat won one.', 'The Paris climate agreement is nonbinding — and Trump said so in his speech announcing the withdrawal.', "We're not.", 'The real number of gang members deported is smaller.', "They haven't.", 'The Obama environmental rule to limit pollution in the country’s waters explicitly excludes puddles.', 'Cohn sold Goldman Sachs stock worth $220 million.', 'Republicans have won four special elections this year, while a Democrat won one.', 'Another coal mine opened in 2014.', "Johnson, who had a different title, didn't say that.", 'Republicans have won four special elections this year, while a Democrat won one.', "CNN's ratings were at a five-year high at the time.", 'Senate bill would have cut the program deeply.', 'The real number of MS-13 gang members who have been deported is smaller.', 'NATO countries agreed to meet defense spending requirements in 2014.', 'Clinton, Carter, Truman, and F.D.R. had signed more at the same point.', 'It is.', 'Presidents Clinton, Carter, Truman, and F.D.R. each had signed more legislation than Trump at the same point in their terms.', 'He reports directly to the attorney general.', "There's no evidence Hillary Clinton was actively involved or benefited from the deal.", 'Many fewer than 45,000 were there, and the attendance was not a record.', 'Tax rates in the United States are below average, overall and for an industrialized country.', "We're not.", 'The increase was 26 percent.', "The decline began before Trump's inauguration.", 'Obama deported millions.', 'The U.S. has a trade surplus with more than 100 countries.', 'Many experts predicted economic growth at least this high.', "Mexico's president says he didn't call Trump.", "It wasn't.", 'Many experts predicted that.', "It's not.", "There's no evidence Hillary Clinton was actively involved in the sale.", "People resigned from Trump's business councils over his Charlottesville comments.", 'Many experts predicted economic growth at least this high.', 'The media does not make up sources.', "Trump's first rally was in New Hampshire", "The U.S. isn't projected to become a net energy exporter until 2026.", "CNN didn't turn off its cameras.", "We're not.", "We're not.", 'The real number is 11,022.', 'The real number is smaller.', "They weren't the strongest ever recorded.", 'Neither agency endorsed him; only their unions did.', 'Strange consistently polled first or second in the Alabama Republican primary.', 'The cost cuts were planned before he became president.', 'All available evidence suggests he would benefit.', 'The real number of small businesses and farmers is vastly smaller.', 'The tax plan would personally benefit Trump\xa0and other wealthy individuals.', 'The Times did not apologize for its Trump coverage.', "We're not.", 'The real number is smaller.', 'The cost cuts were planned before he became president.', 'The cost cuts were planned before he became president.', "We're not.", "The Senate didn't say that.", "We're not.", "We're not.", 'The real number is smaller.', 'The group’s origins date to 2004.', 'Corker asked the Times reporter to record the call; his aides recorded it too.', "We're not.", 'The effectiveness rate is about 60 percent.', "We're not.", 'Ireland has no plans to cut its tax rate.', 'They did call families of soldiers killed in action.', 'Trump himself has bragged about groping women.', "We're not.", "We're not.", 'Taxes in the U.S. are lower than in most developed countries.', "We're not.", "We're not.", 'The group’s origins date to 2004.', "The wife confirmed Representative Frederica Wilson's account.", 'The real number was smaller.', 'Category 5 storms have hit land before.', 'The real number is estimated to be less than 1 million.', 'We have trade surpluses with more than 100 countries.', 'Steyer has financially supported many winning candidates.', "We're not.", 'Several other cities, including New York and Los Angeles, have stronger gun laws.', 'There is no evidence that Democrats "set up" Russian interference in the election.']

In [26]:
for tag in soup.find_all('span',{'class':'short-desc'}):
    d=tag.text.strip()
    st=d.find('“')
    end=d.find('”')
    stat.append(d[st+1:end])
print(stat)

["I wasn't a fan of Iraq. I didn't want to go into Iraq.", 'A reporter for Time magazine — and I have been on their cover 14 or 15 times. I think we have the all-time record in the history of Time magazine.', 'Between 3 million and 5 million illegal votes caused me to lose the popular vote.', 'Now, the audience was the biggest ever. But this crowd was massive. Look how far back it goes. This crowd was massive.', 'Take a look at the Pew reports (which show voter fraud.)', "You had millions of people that now aren't insured anymore.", "So, look, when President Obama was there two weeks ago making a speech, very nice speech. Two people were shot and killed during his speech. You can't have that.", "We've taken in tens of thousands of people. We know nothing about them. They can say they vet them. They didn't vet them. They have no papers. How can you vet somebody when you don't know anything about them and you have no papers? How do you vet them? You can't.", "I cut off hundreds of millions of dollars off one particular plane, hundreds of millions of dollars in a short period of time. It wasn't like I spent, like, weeks, hours, less than hours, and many, many hundreds of millions of dollars. And the plane's going to be better.", 'The coverage about me in the @nytimes and the @washingtonpost has been so false and angry that the Times actually apologized to its dwindling subscribers and readers.', 'The Cuban-Americans, I got 84 percent of that vote.', 'Only 109 people out of 325,000 were detained and held for questioning. Big problems at airports were caused by Delta computer outage.', 'Professional anarchists, thugs and paid protesters are proving the point of the millions of people who voted to MAKE AMERICA GREAT AGAIN!', 'After being forced to apologize for its bad and inaccurate coverage of me after winning the election, the FAKE NEWS @nytimes is still lost!', 'We had 109 people out of hundreds of thousands of travelers and all we did was vet those people very, very carefully.', 'I have already saved more than $700 million when I got involved in the negotiation on the F-35.', "It's gotten to a point where it is not even being reported. And in many cases, the very, very dishonest press doesn't want to report it.", 'The failing @nytimes was forced to apologize to its subscribers for the poor reporting it did on my election win. Now they are worse!', "And the previous administration allowed it to happen because we shouldn't have been in Iraq, but we shouldn't have gotten out the way we got out. It created a vacuum, ISIS was formed.", 'And yet the murder rate in our country is the highest it’s been in 47 years, right? Did you know that? Forty-seven years.', 'I saved more than $600 million. I got involved in negotiation on a fighter jet, the F-35.', 'Chris Cuomo, in his interview with Sen. Blumenthal, never asked him about his long-term lie about his brave ‘service’ in Vietnam. FAKE NEWS!', 'Sen. Richard Blumenthal now misrepresents what Judge Gorsuch told him?', 'I don’t know about it. I haven’t seen it. What report is that?', 'Just leaving Florida. Big crowds of enthusiastic supporters lining the road that the FAKE NEWS media refuses to mention. Very dishonest!', "We got 306 because people came out and voted like they've never seen before so that's the way it goes. I guess it was the biggest Electoral College win since Ronald Reagan.", 'That’s the other thing that was wrong with the travel ban. You had Delta with a massive problem with their computer system at the airports.', 'Walmart announced it will create 10,000 jobs in the United States just this year because of our various plans and initiatives.', 'When WikiLeaks, which I had nothing to do with, comes out and happens to give, they’re not giving classified information.', 'We had a very smooth rollout of the travel ban. But we had a bad court. Got a bad decision.', 'They’re giving stuff — what was said at an office about Hillary cheating on the debates. Which, by the way, nobody mentions. Nobody mentions that Hillary received the questions to the debates.', 'And there was no way to vet those people. There was no documentation. There was no nothing.', "You look at what's happening in Germany, you look at what's happening last night in Sweden. Sweden, who would believe this?", 'By the way, you folks are in here — this place is packed, there are lines that go back six blocks.', 'ICE came and endorsed me.', 'Obamacare covers very few people — and remember, deduct from the number all of the people that had great health care that they loved that was taken away from them — it was taken away from them.', 'Since Obamacare went into effect, nearly half of the insurers are stopped and have stopped from participating in the Obamacare exchanges.', 'On one plane, on a small order of one plane, I saved $725 million. And I would say I devoted about, if I added it up, all those calls, probably about an hour. So I think that might be my highest and best use.', 'And now, based on our very strong and frank discussions, they are beginning to do just that.', 'The E.P.A.’s regulators were putting people out of jobs by the hundreds of thousands.', 'We have begun to drain the swamp of government corruption by imposing a five-year ban on lobbying by executive branch officials.', 'It is so pathetic that the Dems have still not approved my full Cabinet.', 'Terrible! Just found out that Obama had my ‘wires tapped’ in Trump Tower just before the victory. Nothing found. This is McCarthyism!', 'How low has President Obama gone to tap my phones during the very sacred election process. This is Nixon/Watergate. Bad (or sick) guy!', '122 vicious prisoners, released by the Obama Administration from Gitmo, have returned to the battlefield. Just another terrible decision!', "I saved a lot of money on those jets, didn't I? Did I do a good job? More than $725 million on them.", 'First of all, it covers very few people.', 'On the airplanes, I saved $725 million. Probably took me a half an hour if you added up all of the times.', 'I was in Tennessee — I was just telling the folks — and half of the state has no insurance company, and the other half is going to lose the insurance company.', 'With just one negotiation on one set of airplanes, I saved the taxpayers of our country over $700 million.', 'To save taxpayer dollars, I’ve already begun negotiating better contracts for the federal government — saving over $700 million on just one set of airplanes of which there are many sets.', 'I make the statement, everyone goes crazy. The next day they have a massive riot, and death, and problems.', 'NATO, obsolete, because it doesn’t cover terrorism. They fixed that.', 'Well, now, if you take a look at the votes, when I say that, I mean mostly they register wrong — in other words, for the votes, they register incorrectly and/or illegally. And they then vote. You have tremendous numbers of people.', 'Remember when the failing @nytimes apologized to its subscribers, right after the election, because their coverage was so wrong. Now worse!', 'We have a lot of plants going up now in Michigan that were never going to be there if I — if I didn’t win this election, those plants would never even think about going back. They were gone.', 'And I was totally opposed to the war in the Middle East which I think finally has been proven, people tried very hard to say I wasn’t but you’ve seen that it is now improving.', 'Now, my last tweet — you know, the one that you are talking about, perhaps — was the one about being, in quotes, wiretapped, meaning surveilled. Guess what, it is turning out to be true.', 'You have many states coming up where they’re going to have no insurance company. O.K.? It’s already happened in Tennessee. It’s happening in Kentucky. Tennessee only has half coverage. Half the state is gone. They left.', 'If you look at the kind of cost-cutting we’ve been able to achieve with the military and at the same time ordering vast amounts of equipment — saved hundreds of millions of dollars on airplanes, and really billions, because if you take that out over a period of years it’s many billions of dollars — I think we’ve had a tremendous success.', 'I like Steve, but you have to remember he was not involved in my campaign until very late. I had already beaten all the senators and all the governors, and I didn’t know Steve.', "You can't do it faster, because they're obstructing. They're obstructionists. So I have people — hundreds of people that we're trying to get through. I mean you have — you see the backlog. We can't get them through.", 'The New York Times said the word wiretapped in the headline of the first edition. Then they took it out of there fast when they realized.', 'The secretary general and I had a productive discussion about what more NATO can do in the fight against terrorism. I complained about that a long time ago and they made a change, and now they do fight terrorism.', 'Mosul was supposed to last for a week and now they’ve been fighting it for many months and so many more people died.', 'Someone should look into who paid for the small organized rallies yesterday. The election is over!', 'The fake media goes, ‘Donald Trump changed his stance on China.’ I haven’t changed my stance.', "On 90 planes I saved $725 million. It's actually a little bit more than that, but it's $725 million.", 'When WikiLeaks came out ... never heard of WikiLeaks, never heard of it.', 'I want to help our miners while the Democrats are blocking their healthcare.', 'The trade deficit with Mexico is close to $70 billion, even with Canada it’s $17 billion trade deficit with Canada.', "She's running against someone who's going to raise your taxes to the sky, destroy your health care, and he's for open borders — lots of crime.", 'The F-35 fighter jet program — it was way over budget. I’ve saved $725 million plus, just by getting involved in the negotiation.', "As you know, I've been a big critic of China, and I've been talking about currency manipulation for a long time. But I have to tell you that during the election, number one, they stopped.", "I've already saved more than $725 million on a simple order of F-35 planes. I got involved in the negotiation.", "We're also getting NATO countries to finally step up and contribute their fair share. They've begun to increase their contributions by billions of dollars, but we are not going to be satisfied until everyone pays what they owe.", 'When they talk about currency manipulation, and I did say I would call China, if they were, a currency manipulator, early in my tenure. And then I get there. Number one, they — as soon as I got elected, they stopped.', 'I was negotiating to reduce the price of the big fighter jet contract, the F-35, which was totally out of control. I will save billions and billions and billions of dollars.', "I think our side's been proven very strongly. And everybody's talking about it.", "Well, we are protecting pre-existing conditions. And it'll be every good — bit as good on pre-existing conditions as Obamacare.", "The F-35 fighter jet — I saved — I got involved in the negotiation. It's 2,500 jets. I negotiated for 90 planes, lot 10. I got $725 million off the price.", "First of all, since I started running, they haven't increased their — you know, they have not manipulated their currency. I think that was out of respect to me and the campaign.", 'I love buying those planes at a reduced price. I have been really — I have cut billions — I have to tell you this, and they can check, right, Martha? I have cut billions and billions of dollars off plane contracts sitting here.', 'Number two, they’re actually not a currency [manipulator]. You know, since I’ve been talking about currency manipulation with respect to them and other countries, they stopped.', 'We’re the highest-taxed nation in the world.', 'Nobody cares about my tax return except for the reporters.', 'You know we’ve gotten billions of dollars more in NATO than we’re getting. All because of me.', 'But when I did his show, which by the way was very highly rated. It was high — highest rating. The highest rating he’s ever had.', 'Director Clapper reiterated what everybody, including the fake media already knows — there is ‘no evidence’ of collusion w/ Russia and Trump.', 'Again, the story that there was collusion between the Russians & Trump campaign was fabricated by Dems as an excuse for losing the election.', 'When James Clapper himself, and virtually everyone else with knowledge of the witch hunt, says there is no collusion, when does it end?', "I'm cutting the price of airplanes with Lockheed.", 'Just arrived in Italy for the G7. Trip has been very successful. We made and saved the USA many billions of dollars and millions of jobs.', 'China will be allowed to build hundreds of additional coal plants. So, we can’t build the plants, but they can, according to this agreement. India will be allowed to double its coal production by 2020.', 'I’ve just returned from a trip overseas where we concluded nearly $350 billion of military and economic development for the United States, creating hundreds of thousands of jobs.', 'At least 7 dead and 48 wounded in terror attack and Mayor of London says there is ‘no reason to be alarmed!’', 'The Justice Dept. should have stayed with the original Travel Ban, not the watered down, politically correct version they submitted to S.C.', 'Well, the Special Elections are over and those that want to MAKE AMERICA GREAT AGAIN are 5 and O!', "They all say it's 'nonbinding.' Like hell it's nonbinding.", 'Right now, we are one of the highest-taxed nations in the world.', 'You have a gang called MS-13. ... We are moving them out of the country by the thousands, by the thousands.', 'Your insurance companies have all fled the state of Iowa.', "If [farmers] have a puddle in the middle of their field ... it's considered a lake and you can't touch it. ... We got rid of that one, too, O.K.?", 'Gary Cohn just paid $200 million in tax in order to take this job, by the way.', 'We’re 5 and 0.', 'Last week a brand-new coal mine just opened in the state of Pennsylvania, first time in decades, decades.', 'Former Homeland Security Advisor Jeh Johnson is latest top intelligence official to state there was no grand scheme between Trump & Russia.', 'We are 5 and 0 ... in these special elections.', 'Ratings way down!', 'Democrats purposely misstated Medicaid under new Senate bill — actually goes up.', 'General Kelly and his whole group — they’ve gotten rid of 6,000 so far.', 'As a result of this insistence, billions of dollars more have begun to pour into NATO.', 'We’ve signed more bills — and I’m talking about through the legislature — than any president, ever.', 'Um, the Russian investigation — it’s not an investigation, it’s not on me — you know, they’re looking at a lot of things.', 'I heard that Harry Truman was first, and then we beat him. These are approved by Congress. These are not just executive orders.', 'But the F.B.I. person really reports directly to the president of the United States, which is interesting.', 'She did the uranium deal, which is a horrible thing, while she was secretary of state, and got a lot of money.', 'It looks like about 45,000 people. You set a record today.', 'We have the highest taxes anywhere in the world, and this will really bring them down to one of the lowest.', 'We’re the highest-taxed nation in the world', 'We have nearly doubled the number of veterans given approvals to see the doctor of their choice.', 'Since I took office we have cut illegal immigration on our southern border by record numbers. 78 percent.', 'The previous administration enacted an open-door policy to illegal migrants from Central America.  "Welcome in. Come in, please, please.', 'We have trade deficits with almost every country because we had a lot of really bad negotiators making deals with other countries.', '2.6 is a number that nobody thought they’d see for a long period of time.', 'And even the President of Mexico called me  – they said their southern border, very few people are coming because they know they’re not going to get through our border, which is the ultimate compliment.', "And I think to me, maybe the biggest is that GDP for the quarter just released at 2.6 percent. So that's so much higher than anticipated.", 'Economic growth has surged to 2.6% nationwide. You have to understand what that means. Nobody thought that number was going to happen.', 'The Russia story is a total fabrication.', 'Or let them look at the uranium she sold that is now in the hands of very angry Russians.', "We want products made in the country. Now, I have to tell you, some of the folks that will leave, they're leaving out of embarrassment because they make their products outside.", 'Remember, everybody said you won’t bring it up to 1 percent. You won’t bring it up to 1.2 percent.', "I mean truly dishonest people in the media and the fake media, they make up stories. They have no sources in many cases. They say 'a source says'  – there is no such thing.", 'As everybody here remembers, this was the scene of my first rally speech, right?', 'We have become an energy exporter for the first time ever just recently.', "Look back there, the live red lights. They're turning those suckers off fast out there. They're turning those lights off fast. Like CNN.", 'The taxes are crazy  – the highest-taxed nation in the world.', 'We are the highest taxed nation in the world - that will change.', 'Our incredible U.S. Coast Guard saved more than 15,000 lives last week with Harvey.', "Also with the fact that I know in the case of FEMA and the case of Coast Guard, the job you've done in saving people, saving lives.  As an example, in Harvey in Texas, we talked  – over 16,000 lives.", 'And in Florida you got hit with the strongest winds ever recorded.', "We've been dealing with ICE, we've been dealing with the Border Patrol. They both endorsed me.", "So he started off here, he was in third or fourth, he went to third, second, and now it's like almost pretty even.", "With the F-35 fighter plane  – me, myself  – I've saved hundreds of millions of dollars in negotiating.", 'I’m doing the right thing, and it’s not good for me.', 'To protect millions of small businesses and the American farmer, we are finally ending the crushing, the horrible, the unfair estate tax.', "No, I don't benefit. I don't benefit. In fact, very very strongly, as you see, I think there's very little benefit for people of wealth.", 'Facebook was always anti-Trump.The Networks were always anti-Trump hence,Fake News, @nytimes(apologized) & @WaPo were anti-Trump.', "I mean right now, we're the highest-taxed nation in the world.", 'But the Coast Guard itself saved in Texas 16,000 lives, and they went right through that hurricane.', "But that's an expensive plane that you can't see. And as you probably heard, we cut the price very substantially  – something that other administrations would never have done, that I can tell you.", 'I was able to reduce the price of the Lockheed by billions of dollars.', "We're the highest-taxed developed nation in the world, probably the highest-taxed nation in the world.", 'They also just said that there has been absolutely no collusion. They just said that. Yesterday. Two days ago. Senate. There has been no collusion.', "This tax cut and tax reform is going very well, and it's going to be a tremendous boost for our country, including the fact that we're the highest-taxed nation in the world.", "We're the highest-taxed nation in the world.", 'The Coast Guard, in Texas, and all over, but with the job they did in Texas, I saw, they saved 16,000 lives.', "Obama should have never gotten out the way he got out. That's how ISIS formed.", "The Failing @nytimes set Liddle' Bob Corker up by recording his conversation. Was made to sound a fool, and that's what I am dealing with!", "We're the highest-taxed nation in the world.", "We

In [27]:
print('No of records:',len(date))
print('==============')
for i in range(len(date)):
    print('Date: ',date[i])
    print('Statement: ',stat[i])
    print('Truth: ',tt[i])
    print('--------------')

No of records: 180
==============
Date:  Jan. 21
Statement:  I wasn't a fan of Iraq. I didn't want to go into Iraq.
Truth:  He was for an invasion before he was against it.
--------------
Date:  Jan. 21
Statement:  A reporter for Time magazine — and I have been on their cover 14 or 15 times. I think we have the all-time record in the history of Time magazine.
Truth:  Trump was on the cover 11 times and Nixon appeared 55 times.
--------------
Date:  Jan. 23
Statement:  Between 3 million and 5 million illegal votes caused me to lose the popular vote.
Truth:  There's no evidence of illegal voting.
--------------
Date:  Jan. 25
Statement:  Now, the audience was the biggest ever. But this crowd was massive. Look how far back it goes. This crowd was massive.
Truth:  Official aerial photos show Obama's 2009 inauguration was much more heavily attended.
--------------
Date:  Jan. 25
Statement:  Take a look at the Pew reports (which show voter fraud.)
Truth:  The report never mentioned voter fraud.
--------------
Date:  Jan. 25
Statement:  You had millions of people that now aren't insured anymore.
Truth:  The real number is less than 1 million, according to the Urban Institute.
--------------
Date:  Jan. 25
Statement:  So, look, when President Obama was there two weeks ago making a speech, very nice speech. Two people were shot and killed during his speech. You can't have that.
Truth:  There were no gun homicide victims in Chicago that day.
--------------
Date:  Jan. 26
Statement:  We've taken in tens of thousands of people. We know nothing about them. They can say they vet them. They didn't vet them. They have no papers. How can you vet somebody when you don't know anything about them and you have no papers? How do you vet them? You can't.
Truth:  Vetting lasts up to two years.
--------------
Date:  Jan. 26
Statement:  I cut off hundreds of millions of dollars off one particular plane, hundreds of millions of dollars in a short period of time. It wasn't like I spent, like, weeks, hours, less than hours, and many, many hundreds of millions of dollars. And the plane's going to be better.
Truth:  Most of the cuts were already planned.
--------------
Date:  Jan. 28
Statement:  The coverage about me in the @nytimes and the @washingtonpost has been so false and angry that the Times actually apologized to its dwindling subscribers and readers.
Truth:  It never apologized.
--------------
Date:  Jan. 29
Statement:  The Cuban-Americans, I got 84 percent of that vote.
Truth:  There is no support for this.
--------------
Date:  Jan. 30
Statement:  Only 109 people out of 325,000 were detained and held for questioning. Big problems at airports were caused by Delta computer outage.
Truth:  At least 746 people were detained and processed, and the Delta outage happened two days later.
--------------
Date:  Feb. 3
Statement:  Professional anarchists, thugs and paid protesters are proving the point of the millions of people who voted to MAKE AMERICA GREAT AGAIN!
Truth:  There is no evidence of paid protesters.
--------------
Date:  Feb. 4
Statement:  After being forced to apologize for its bad and inaccurate coverage of me after winning the election, the FAKE NEWS @nytimes is still lost!
Truth:  It never apologized.
--------------
Date:  Feb. 5
Statement:  We had 109 people out of hundreds of thousands of travelers and all we did was vet those people very, very carefully.
Truth:  About 60,000 people were affected.
--------------
Date:  Feb. 6
Statement:  I have already saved more than $700 million when I got involved in the negotiation on the F-35.
Truth:  Much of the price drop was projected before Trump took office.
--------------
Date:  Feb. 6
Statement:  It's gotten to a point where it is not even being reported. And in many cases, the very, very dishonest press doesn't want to report it.
Truth:  Terrorism has been reported on, often in detail.
--------------
Date:  Feb. 6
Statement:  The failing @nytimes was forced to apologize to its subscribers for the poor reporting it did on my election win. Now they are worse!
Truth:  It didn't apologize.
--------------
Date:  Feb. 6
Statement:  And the previous administration allowed it to happen because we shouldn't have been in Iraq, but we shouldn't have gotten out the way we got out. It created a vacuum, ISIS was formed.
Truth:  The group’s origins date to 2004.
--------------
Date:  Feb. 7
Statement:  And yet the murder rate in our country is the highest it’s been in 47 years, right? Did you know that? Forty-seven years.
Truth:  It was higher in the 1980s and '90s.
--------------
Date:  Feb. 7
Statement:  I saved more than $600 million. I got involved in negotiation on a fighter jet, the F-35.
Truth:  The Defense Department projected this price drop before Trump took office.
--------------
Date:  Feb. 9
Statement:  Chris Cuomo, in his interview with Sen. Blumenthal, never asked him about his long-term lie about his brave ‘service’ in Vietnam. FAKE NEWS!
Truth:  It was part of Cuomo's first question.
--------------
Date:  Feb. 9
Statement:  Sen. Richard Blumenthal now misrepresents what Judge Gorsuch told him?
Truth:  The Gorsuch comments were later corroborated.
--------------
Date:  Feb. 10
Statement:  I don’t know about it. I haven’t seen it. What report is that?
Truth:  Trump knew about Flynn's actions for weeks.
--------------
Date:  Feb. 12
Statement:  Just leaving Florida. Big crowds of enthusiastic supporters lining the road that the FAKE NEWS media refuses to mention. Very dishonest!
Truth:  The media did cover it.
--------------
Date:  Feb. 16
Statement:  We got 306 because people came out and voted like they've never seen before so that's the way it goes. I guess it was the biggest Electoral College win since Ronald Reagan.
Truth:  George H.W. Bush, Bill Clinton and Barack Obama all won bigger margins in the Electoral College.
--------------
Date:  Feb. 16
Statement:  That’s the other thing that was wrong with the travel ban. You had Delta with a massive problem with their computer system at the airports.
Truth:  Delta's problems happened two days later.
--------------
Date:  Feb. 16
Statement:  Walmart announced it will create 10,000 jobs in the United States just this year because of our various plans and initiatives.
Truth:  The jobs are a result of its investment plans announced in Oct. 2016.
--------------
Date:  Feb. 16
Statement:  When WikiLeaks, which I had nothing to do with, comes out and happens to give, they’re not giving classified information.
Truth:  Not always. They have released classified information in the past.
--------------
Date:  Feb. 16
Statement:  We had a very smooth rollout of the travel ban. But we had a bad court. Got a bad decision.
Truth:  The rollout was chaotic.
--------------
Date:  Feb. 16
Statement:  They’re giving stuff — what was said at an office about Hillary cheating on the debates. Which, by the way, nobody mentions. Nobody mentions that Hillary received the questions to the debates.
Truth:  It was widely covered.
--------------
Date:  Feb. 18
Statement:  And there was no way to vet those people. There was no documentation. There was no nothing.
Truth:  Refugees receive multiple background checks, taking up to two years.
--------------
Date:  Feb. 18
Statement:  You look at what's happening in Germany, you look at what's happening last night in Sweden. Sweden, who would believe this?
Truth:  Trump implied there was a terror attack in Sweden, but there was no such attack.
--------------
Date:  Feb. 24
Statement:  By the way, you folks are in here — this place is packed, there are lines that go back six blocks.
Truth:  There was no evidence of long lines.
--------------
Date:  Feb. 24
Statement:  ICE came and endorsed me.
Truth:  Only its union did.
--------------
Date:  Feb. 24
Statement:  Obamacare covers very few people — and remember, deduct from the number all of the people that had great health care that they loved that was taken away from them — it was taken away from them.
Truth:  Obamacare increased coverage by a net of about 20 million.
--------------
Date:  Feb. 27
Statement:  Since Obamacare went into effect, nearly half of the insurers are stopped and have stopped from participating in the Obamacare exchanges.
Truth:  Many fewer pulled out.
--------------
Date:  Feb. 27
Statement:  On one plane, on a small order of one plane, I saved $725 million. And I would say I devoted about, if I added it up, all those calls, probably about an hour. So I think that might be my highest and best use.
Truth:  Much of the price cut was already projected.
--------------
Date:  Feb. 28
Statement:  And now, based on our very strong and frank discussions, they are beginning to do just that.
Truth:  NATO countries agreed to meet defense spending requirements in 2014.
--------------
Date:  Feb. 28
Statement:  The E.P.A.’s regulators were putting people out of jobs by the hundreds of thousands.
Truth:  There's no evidence that the Waters of the United States rule caused severe job losses.
--------------
Date:  Feb. 28
Statement:  We have begun to drain the swamp of government corruption by imposing a five-year ban on lobbying by executive branch officials.
Truth:  They can't lobby their former agency but can still become lobbyists.
--------------
Date:  March 3
Statement:  It is so pathetic that the Dems have still not approved my full Cabinet.
Truth:  Paperwork for the last two candidates was still not submitted to the Senate.
--------------
Date:  March 4
Statement:  Terrible! Just found out that Obama had my ‘wires tapped’ in Trump Tower just before the victory. Nothing found. This is McCarthyism!
Truth:  There's no evidence of a wiretap.
--------------
Date:  March 4
Statement:  How low has President Obama gone to tap my phones during the very sacred election process. This is Nixon/Watergate. Bad (or sick) guy!
Truth:  There's no evidence of a wiretap.
--------------
Date:  March 7
Statement:  122 vicious prisoners, released by the Obama Administration from Gitmo, have returned to the battlefield. Just another terrible decision!
Truth:  113 of them were released by President George W. Bush.
--------------
Date:  March 13
Statement:  I saved a lot of money on those jets, didn't I? Did I do a good job? More than $725 million on them.
Truth:  Much of the cost cuts were planned before Trump.
--------------
Date:  March 13
Statement:  First of all, it covers very few people.
Truth:  About 20 million people gained insurance under Obamacare.
--------------
Date:  March 15
Statement:  On the airplanes, I saved $725 million. Probably took me a half an hour if you added up all of the times.
Truth:  Much of the cost cuts were planned before Trump.
--------------
Date:  March 17
Statement:  I was in Tennessee — I was just telling the folks — and half of the state has no insurance company, and the other half is going to lose the insurance company.
Truth:  There's at least one insurer in every Tennessee county.
--------------
Date:  March 20
Statement:  With just one negotiation on one set of airplanes, I saved the taxpayers of our country over $700 million.
Truth:  Much of the cost cuts were planned before Trump.
--------------
Date:  March 21
Statement:  To save taxpayer dollars, I’ve already begun negotiating better contracts for the federal government — saving over $700 million on just one set of airplanes of which there are many sets.
Truth:  Much of the cost cuts were planned before Trump.
--------------
Date:  March 22
Statement:  I make the statement, everyone goes crazy. The next day they have a massive riot, and death, and problems.
Truth:  Riots in Sweden broke out two days later and there were no deaths.
--------------
Date:  March 22
Statement:  NATO, obsolete, because it doesn’t cover terrorism. They fixed that.
Truth:  It has fought terrorism since the 1980s.
--------------
Date:  March 22
Statement:  Well, now, if you take a look at the votes, when I say that, I mean mostly they register wrong — in other words, for the votes, they register incorrectly and/or illegally. And they then vote. You have tremendous numbers of people.
Truth:  There's no evidence of widespread voter fraud.
--------------
Date:  March 29
Statement:  Remember when the failing @nytimes apologized to its subscribers, right after the election, because their coverage was so wrong. Now worse!
Truth:  It didn't apologize.
--------------
Date:  March 31
Statement:  We have a lot of plants going up now in Michigan that were never going to be there if I — if I didn’t win this election, those plants would never even think about going back. They were gone.
Truth:  These investments were already planned.
--------------
Date:  April 2
Statement:  And I was totally opposed to the war in the Middle East which I think finally has been proven, people tried very hard to say I wasn’t but you’ve seen that it is now improving.
Truth:  He was for an invasion before he was against it.
--------------
Date:  April 2
Statement:  Now, my last tweet — you know, the one that you are talking about, perhaps — was the one about being, in quotes, wiretapped, meaning surveilled. Guess what, it is turning out to be true.
Truth:  There is still no evidence.
--------------
Date:  April 5
Statement:  You have many states coming up where they’re going to have no insurance company. O.K.? It’s already happened in Tennessee. It’s happening in Kentucky. Tennessee only has half coverage. Half the state is gone. They left.
Truth:  Every marketplace region in Tennessee had at least one insurer.
--------------
Date:  April 6
Statement:  If you look at the kind of cost-cutting we’ve been able to achieve with the military and at the same time ordering vast amounts of equipment — saved hundreds of millions of dollars on airplanes, and really billions, because if you take that out over a period of years it’s many billions of dollars — I think we’ve had a tremendous success.
Truth:  Much of the price cuts were already projected.
--------------
Date:  April 11
Statement:  I like Steve, but you have to remember he was not involved in my campaign until very late. I had already beaten all the senators and all the governors, and I didn’t know Steve.
Truth:  He knew Steve Bannon since 2011.
--------------
Date:  April 12
Statement:  You can't do it faster, because they're obstructing. They're obstructionists. So I have people — hundreds of people that we're trying to get through. I mean you have — you see the backlog. We can't get them through.
Truth:  At this point, he had not nominated anyone for hundreds of positions.
--------------
Date:  April 12
Statement:  The New York Times said the word wiretapped in the headline of the first edition. Then they took it out of there fast when they realized.
Truth:  There were separate headlines for print and web, but neither were altered.
--------------
Date:  April 12
Statement:  The secretary general and I had a productive discussion about what more NATO can do in the fight against terrorism. I complained about that a long time ago and they made a change, and now they do fight terrorism.
Truth:  NATO has been engaged in counterterrorism efforts since the 1980s.
--------------
Date:  April 12
Statement:  Mosul was supposed to last for a week and now they’ve been fighting it for many months and so many more people died.
Truth:  The campaign was expected to take months.
--------------
Date:  April 16
Statement:  Someone should look into who paid for the small organized rallies yesterday. The election is over!
Truth:  There's no evidence of paid protesters.
--------------
Date:  April 18
Statement:  The fake media goes, ‘Donald Trump changed his stance on China.’ I haven’t changed my stance.
Truth:  He did.
--------------
Date:  April 21
Statement:  On 90 planes I saved $725 million. It's actually a little bit more than that, but it's $725 million.
Truth:  Much of the price cuts were already projected.
--------------
Date:  April 21
Statement:  When WikiLeaks came out ... never heard of WikiLeaks, never heard of it.
Truth:  He criticized it as early as 2010.
--------------
Date:  April 27
Statement:  I want to help our miners while the Democrats are blocking their healthcare.
Truth:  The bill to extend health benefits for certain coal miners was introduced by a Democrat and was co-sponsored by mostly Democrats.
--------------
Date:  April 28
Statement:  The trade deficit with Mexico is close to $70 billion, even with Canada it’s $17 billion trade deficit with Canada.
Truth:  The U.S. had an $8.1 billion trade surplus, not deficit, with Canada in 2016.
--------------
Date:  April 28
Statement:  She's running against someone who's going to raise your taxes to the sky, destroy your health care, and he's for open borders — lots of crime.
Truth:  Those are not Jon Ossoff's positions.
--------------
Date:  April 28
Statement:  The F-35 fighter jet program — it was way over budget. I’ve saved $725 million plus, just by getting involved in the negotiation.
Truth:  Much of the price cuts were planned before Trump.
--------------
Date:  April 29
Statement:  As you know, I've been a big critic of China, and I've been talking about currency manipulation for a long time. But I have to tell you that during the election, number one, they stopped.
Truth:  China stopped years ago.
--------------
Date:  April 29
Statement:  I've already saved more than $725 million on a simple order of F-35 planes. I got involved in the negotiation.
Truth:  Much of the price cuts were planned before Trump.
--------------
Date:  April 29
Statement:  We're also getting NATO countries to finally step up and contribute their fair share. They've begun to increase their contributions by billions of dollars, but we are not going to be satisfied until everyone pays what they owe.
Truth:  The deal was struck in 2014.
--------------
Date:  April 29
Statement:  When they talk about currency manipulation, and I did say I would call China, if they were, a currency manipulator, early in my tenure. And then I get there. Number one, they — as soon as I got elected, they stopped.
Truth:  China stopped in 2014.
--------------
Date:  April 29
Statement:  I was negotiating to reduce the price of the big fighter jet contract, the F-35, which was totally out of control. I will save billions and billions and billions of dollars.
Truth:  Most of the cuts were planned before Trump.
--------------
Date:  April 29
Statement:  I think our side's been proven very strongly. And everybody's talking about it.
Truth:  There's still no evidence Trump's phones were tapped.
--------------
Date:  May 1
Statement:  Well, we are protecting pre-existing conditions. And it'll be every good — bit as good on pre-existing conditions as Obamacare.
Truth:  The bill weakens protections for people with pre-existing conditions.
--------------
Date:  May 1
Statement:  The F-35 fighter jet — I saved — I got involved in the negotiation. It's 2,500 jets. I negotiated for 90 planes, lot 10. I got $725 million off the price.
Truth:  Much of the price cuts were planned before Trump.
--------------
Date:  May 1
Statement:  First of all, since I started running, they haven't increased their — you know, they have not manipulated their currency. I think that was out of respect to me and the campaign.
Truth:  China stopped years ago.
--------------
Date:  May 2
Statement:  I love buying those planes at a reduced price. I have been really — I have cut billions — I have to tell you this, and they can check, right, Martha? I have cut billions and billions of dollars off plane contracts sitting here.
Truth:  Much of the cost cuts were planned before Trump.
--------------
Date:  May 4
Statement:  Number two, they’re actually not a currency [manipulator]. You know, since I’ve been talking about currency manipulation with respect to them and other countries, they stopped.
Truth:  China stopped years ago.
--------------
Date:  May 4
Statement:  We’re the highest-taxed nation in the world.

In [28]:
import pandas as pd
df=pd.DataFrame({'Date':date,
                 'Statement':stat,
                 'Truth Text':tt})
df

,Date,Statement,Truth Text
0,Jan. 21,I wasn't a fan of Iraq. I didn't want to go in...,He was for an invasion before he was against it.
1,Jan. 21,A reporter for Time magazine — and I have been...,Trump was on the cover 11 times and Nixon appe...
2,Jan. 23,Between 3 million and 5 million illegal votes ...,There's no evidence of illegal voting.
3,Jan. 25,"Now, the audience was the biggest ever. But th...",Official aerial photos show Obama's 2009 inaug...
4,Jan. 25,Take a look at the Pew reports (which show vot...,The report never mentioned voter fraud.
...,...,...,...
175,Oct. 25,We have trade deficits with almost everybody.,We have trade surpluses with more than 100 cou...
176,Oct. 27,"Wacky & totally unhinged Tom Steyer, who has b...",Steyer has financially supported many winning ...
177,Nov. 1,"Again, we're the highest-taxed nation, just ab...",We're not.
178,Nov. 7,When you look at the city with the strongest g...,"Several other cities, including New York and L..."
179,Nov. 11,"I'd rather have him – you know, work with him...","There is no evidence that Democrats ""set up"" R..."

In [29]:
# Bring the data of jan 25.
df.loc[df['Date']=='Jan. 25']

,Date,Statement,Truth Text
3,Jan. 25,"Now, the audience was the biggest ever. But th...",Official aerial photos show Obama's 2009 inaug...
4,Jan. 25,Take a look at the Pew reports (which show vot...,The report never mentioned voter fraud.
5,Jan. 25,You had millions of people that now aren't ins...,"The real number is less than 1 million, accord..."
6,Jan. 25,"So, look, when President Obama was there two w...",There were no gun homicide victims in Chicago ...

In [3]:
import requests
url='https://www.politifact.com/personalities/donald-trump/'
source=requests.get(url)
print(source.status_code)
# print(source.text)
print(source.content)

200

In [7]:
import bs4
import requests
import pandas as pd
url='https://www.politifact.com/personalities/donald-trump/'
source=requests.get(url)
soup=bs4.BeautifulSoup(source.text,'html.parser')
print(source.status_code)

200

### 200 - ok
### 403 - Forbidden
### 404 - page not found
### 500 - server error

In [10]:
soup.title.text

'PolitiFact | Donald Trump'

In [12]:
for i in soup.find_all('a'):
    if 'href' in i.attrs:
        print(i['href'])

/
#
/membership/
/california/
/florida/
/iowa/
/michigan/
/new-hampshire/
/new-york/
/north-carolina/
/pennsylvania/
/texas/
/west-virginia/
/wisconsin/
/issues/
/factchecks/list/?speaker_type=SOCIAL
/coronavirus/
/health-check/
/immigration/
https://www.politifact.com/article/2022/jun/09/political-extremism-public-square-resource-journal/
/taxes/
/marijuana/
/environment/
/crime/
/guns/
/foreign-policy/
/lgbtq/
/personalities/donald-trump/
/personalities/jd-vance/
/personalities/mitch-mcconnell/
/personalities/mike-johnson/
/personalities/joe-biden/
/punditfact/
/personalities/tucker-carlson/
/personalities/sean-hannity/
/personalities/rachel-maddow/
/personalities/blog-posting/
/videos/
/elections/
/factchecks/list/?ruling=true
/factchecks/list/?ruling=mostly-true
/factchecks/list/?ruling=half-true
/factchecks/list/?ruling=barely-true
/factchecks/list/?ruling=false
/factchecks/list/?ruling=pants-fire
/truth-o-meter/promises/maga-meter-tracking-donald-trumps-2024-promises/?ruling=true
/truth-o-meter/promises/biden-promise-tracker/?ruling=true
/truth-o-meter/promises/trumpometer/?ruling=true
/truth-o-meter/promises/obameter/?ruling=true
/truth-o-meter/promises/list/
/article/2018/feb/12/principles-truth-o-meter-politifacts-methodology-i/
/staff/
/espanol/
/who-pays-for-politifact/
/media-kit/
/suggest/statement/
/corrections-and-updates/
/signup/
/membership/
https://twitter.com/Politifact/
https://www.facebook.com/politifact/
https://bsky.app/profile/politifact.bsky.social

/
/espanol/
/membership/
https://www.donaldjtrump.com/
/factchecks/list/?category=&ruling=true&speaker=donald-trump
/factchecks/list/?category=&ruling=mostly-true&speaker=donald-trump
/factchecks/list/?category=&ruling=half-true&speaker=donald-trump
/factchecks/list/?category=&ruling=barely-true&speaker=donald-trump
/factchecks/list/?category=&ruling=false&speaker=donald-trump
/factchecks/list/?category=&ruling=pants-fire&speaker=donald-trump
/article/2018/feb/12/principles-truth-o-meter-politifacts-methodology-i/
/factchecks/list/
/personalities/donald-trump/
/factchecks/2026/jun/12/donald-trump/nassau-county-new-york-blakeman-republicans/
/personalities/donald-trump/
/factchecks/2026/jun/08/donald-trump/California-election-LA-governor-Spencer-Pratt/
/personalities/donald-trump/
/factchecks/2026/jun/03/donald-trump/cognitive-test-montreal-intelligence/
/personalities/donald-trump/
/factchecks/2026/may/20/donald-trump/legal-settlement-fund-weaponization-justice-jan-6/
/personalities/donald-trump/
/factchecks/2026/may/08/donald-trump/gasoline-prices-falling-crude-oil/
/factchecks/list/?speaker=donald-trump
/factchecks/list/
/personalities/social-media/
/factchecks/2025/jul/08/social-media/national-weather-service-noaa-cuts-texas-flood/
/personalities/viral-image/
/factchecks/2025/apr/04/viral-image/elon-musk-didnt-target-trumps-golf-trips-in-an-x-p/
/personalities/viral-image/
/factchecks/2025/apr/04/viral-image/video-shows-danish-lawmakers-laughing-at-prime-min/
/personalities/viral-image/
/factchecks/2025/apr/04/viral-image/this-isnt-a-real-truth-social-post-from-trump-abou/
/personalities/viral-image/
/factchecks/2025/feb/14/viral-image/old-photo-mischaracterized-as-showing-tulsi-gabbar/
/factchecks/list/?target=donald-trump
/article/2018/feb/12/principles-truth-o-meter-politifacts-methodology-i/
/staff/
/who-pays-for-politifact/
/membership/
#
#
/personalities/donald-trump/
/personalities/jd-vance/
/personalities/mitch-mcconnell/
/personalities/mike-johnson/
/personalities/joe-biden/
/california/
/florida/
/iowa/
/michigan/
/new-hampshire/
/new-york/
/north-carolina/
/pennsylvania/
/texas/
/west-virginia/
/wisconsin/
/article/2018/feb/12/principles-truth-o-meter-politifacts-methodology-i/
/staff/
/espanol/
/who-pays-for-politifact/
/media-kit/
/corrections-and-updates/
/signup/
/rss/social/
/rss/factchecks/
/suggest/statement/
https://twitter.com/Politifact/
https://www.facebook.com/politifact/
https://bsky.app/profile/politifact.bsky.social
/copyright/
/privacy/
/copyright/
https://www.facebook.com/sharer/sharer.php?app_id=454308342057334&sdk=joey&u=&display=popup&ref=plugin&src=share_button
https://twitter.com/share?text=&url=
https://bsky.app/intent/compose?text=
/cdn-cgi/l/email-protection#09367a7c6b636c6a7d342f6b666d7034292429

In [14]:
for i in soup.find_all('img'):
    if 'src' in i.attrs:
        print(i['src'])

//www.facebook.com/tr?id=292850974235854&ev=PageView&noscript=1
https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/c280818361ed0d71eb3d5e5a224e01e8.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/c280818361ed0d71eb3d5e5a224e01e8.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/80bd15ec0d50cf908299031c9790109e.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/c1c32c5a2e0a94447f75d2e6dfe5573d.jpg
https://static.politifact.com/img/meter-barely-true-th.jpg
https://static.politifact.com/img/meter-barely-true.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/80bd15ec0d50cf908299031c9790109e.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/c1c32c5a2e0a94447f75d2e6dfe5573d.jpg
https://static.politifact.com/img/meter-pants-fire-th.jpg
https://static.politifact.com/img/meter-pants-fire.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/80bd15ec0d50cf908299031c9790109e.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/c1c32c5a2e0a94447f75d2e6dfe5573d.jpg
https://static.politifact.com/img/meter-false-th.jpg
https://static.politifact.com/img/meter-false.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/80bd15ec0d50cf908299031c9790109e.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/c1c32c5a2e0a94447f75d2e6dfe5573d.jpg
https://static.politifact.com/img/meter-false-th.jpg
https://static.politifact.com/img/meter-false.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/80bd15ec0d50cf908299031c9790109e.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/c1c32c5a2e0a94447f75d2e6dfe5573d.jpg
https://static.politifact.com/img/meter-false-th.jpg
https://static.politifact.com/img/meter-false.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/Social_media_apps_shutterstock/3773b507a544b9625369bf10fcd6c213.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/Social_media_apps_shutterstock/2189518027d0806055e97ed66491ccdf.jpg
https://static.politifact.com/img/meter-barely-true-th.jpg
https://static.politifact.com/img/meter-barely-true.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/shutterstock_566530930/854f64048ec8b1dcc6b08d7834a6decf.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/shutterstock_566530930/bba9eaa02f7503d99f63d596a3e0db2d.jpg
https://static.politifact.com/img/meter-false-th.jpg
https://static.politifact.com/img/meter-false.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/shutterstock_566530930/854f64048ec8b1dcc6b08d7834a6decf.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/shutterstock_566530930/bba9eaa02f7503d99f63d596a3e0db2d.jpg
https://static.politifact.com/img/meter-false-th.jpg
https://static.politifact.com/img/meter-false.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/shutterstock_566530930/854f64048ec8b1dcc6b08d7834a6decf.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/shutterstock_566530930/bba9eaa02f7503d99f63d596a3e0db2d.jpg
https://static.politifact.com/img/meter-false-th.jpg
https://static.politifact.com/img/meter-false.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/shutterstock_566530930/854f64048ec8b1dcc6b08d7834a6decf.jpg
https://static.politifact.com/CACHE/images/politifact/mugs/shutterstock_566530930/bba9eaa02f7503d99f63d596a3e0db2d.jpg
https://static.politifact.com/img/meter-false-th.jpg
https://static.politifact.com/img/meter-false.jpg
https://static.politifact.com/img/logo-footer.png

In [22]:
soup.find('meta',{'name':'description'})['content']

'PolitiFact is a fact-checking website that rates the accuracy of claims by elected officials and others on its Truth-O-Meter.'

In [18]:
soup.find('h1').text

'Donald Trump'

In [20]:
date=[]
name=[]

for i in soup.find_all('footer',{'class':'m-statement__footer'}):
    data=i.text.strip().split(' • ')
    name.append(data[0][3:])
    date.append(data[1])
print('Name: ',name)
print()
print('Date: ',date)

Name:  ['Conor Amendola', 'Amy Sherman', 'Louis Jacobson', 'Louis Jacobson', 'Louis Jacobson', 'Louis Jacobson', "Ciara O'Rourke", "Ciara O'Rourke", "Ciara O'Rourke", "Ciara O'Rourke"]

Date:  ['June 12, 2026', 'June 8, 2026', 'June 3, 2026', 'May 20, 2026', 'May 8, 2026', 'July 8, 2025', 'April 4, 2025', 'April 4, 2025', 'April 4, 2025', 'February 14, 2025']

In [40]:
cl=[]
for tag in soup.find_all(True):
    if 'class' in tag.attrs:
        if tag['class'] not in cl:
            cl.append(tag['class'])
cl

[[],
 ['global-wrapper'],
 ['o-header'],
 ['o-header__inner'],
 ['o-header__branding'],
 ['m-branding'],
 ['m-branding__logo'],
 ['c-icon'],
 ['m-branding__subline'],
 ['m-branding__claim'],
 ['o-header__menu'],
 ['c-burger'],
 ['c-burger__lines'],
 ['c-burger__value'],
 ['o-header__donate'],
 ['c-button', 'c-button--small', 'show-for-large'],
 ['t-menu'],
 ['t-menu__content'],
 ['o-menu-list'],
 ['o-menu-list__inner'],
 ['o-menu-list__item'],
 ['m-togglist'],
 ['m-togglist__checkbox', 'show-for-sr'],
 ['m-togglist__label'],
 ['m-togglist__panel'],
 ['m-togglist__list'],
 ['o-socializer'],
 ['o-socializer__item', 'hide-for-large'],
 ['c-button'],
 ['o-socializer__item', 'o-socializer__social'],
 ['m-follow'],
 ['m-follow__title'],
 ['m-follow__items'],
 ['o-socializer__item', 'o-socializer__subscribe'],
 ['m-subscribe'],
 ['m-subscribe__title'],
 ['c-input'],
 ['c-input__inner'],
 ['c-input__field'],
 ['c-button', 'c-button--hollow'],
 ['o-header__search'],
 ['m-search'],
 ['m-search__checkbox', 'show-for-sr'],
 ['m-search__toggle'],
 ['m-search__content'],
 ['m-search__form'],
 ['m-search__input'],
 ['m-search__submit'],
 ['lang-sub-nav', 'm-togglist__list'],
 ['global-content'],
 ['o-disruptor', 'is-active'],
 ['o-disruptor__close'],
 ['o-disruptor__wrapper'],
 ['o-disruptor__content'],
 ['m-disruptor-content'],
 ['m-disruptor-content__title'],
 ['m-disruptor-content__link'],
 ['o-disruptor__form'],
 ['m-disruptor-form'],
 ['m-disruptor-form__title'],
 ['m-disruptor-form__items'],
 ['m-disruptor-form__item'],
 ['c-input', 'c-input--light'],
 ['c-select', 'c-select--light'],
 ['c-select__inner'],
 ['m-billboard'],
 ['m-pageheader', 'm-pageheader--rounded'],
 ['m-pageheader__wrapper'],
 ['m-pageheader__inner'],
 ['m-pageheader__img'],
 ['c-image'],
 ['c-image__thumb'],
 ['c-image__original'],
 ['m-pageheader__header'],
 ['m-pageheader__title'],
 ['m-pageheader__body'],
 ['m-pageheader__footer'],
 ['o-platform', 'o-platform--is-wide'],
 ['o-platform__inner'],
 ['o-platform__header'],
 ['c-title', 'c-title--section'],
 ['o-platform__content'],
 ['m-scorecard', 'o-platform--is-wide'],
 ['m-scorecard__item'],
 ['m-scorecard__title'],
 ['c-info'],
 ['c-icon', 'm-scorecard--is-boxed'],
 ['m-scorecard__pond'],
 ['m-scorecard__bar', 'u-background--true'],
 ['m-scorecard__body'],
 ['m-scorecard__value'],
 ['m-scorecard__checks'],
 ['m-scorecard__bar', 'u-background--mostly-true'],
 ['m-scorecard__bar', 'u-background--half-true'],
 ['m-scorecard__bar', 'u-background--mostly-false'],
 ['m-scorecard__bar', 'u-background--false'],
 ['m-scorecard__bar', 'u-background--fire'],
 ['o-platform__footer'],
 ['o-listicle'],
 ['o-listicle__inner'],
 ['o-listicle__header'],
 ['o-listicle__title'],
 ['o-listicle__content'],
 ['t-row'],
 ['c-select', 'c-select--light', 'rounded-select-label'],
 ['c-select__inner', 'rounded-select'],
 ['c-select'],
 ['o-listicle__list'],
 ['o-listicle__item'],
 ['m-statement', 'm-statement--is-medium', 'm-statement--false'],
 ['m-statement__author'],
 ['m-statement__avatar'],
 ['m-statement__image'],
 ['m-statement__meta'],
 ['m-statement__name'],
 ['m-statement__desc'],
 ['m-statement__content'],
 ['m-statement__body'],
 ['m-statement__quote-wrap'],
 ['m-statement__quote'],
 ['m-statement__meter'],
 ['m-statement__footer'],
 ['m-statement', 'm-statement--is-medium', 'm-statement--mostly-true'],
 ['o-listicle__more'],
 ['c-button', 'c-button--large', 'c-button--hollow'],
 ['m-statement', 'm-statement--is-medium', 'm-statement--mostly-false'],
 ['t-row__left'],
 ['t-row__center'],
 ['t-row__right'],
 ['m-introduction'],
 ['m-introduction__inner'],
 ['m-introduction__content'],
 ['m-intoduction__header'],
 ['m-introduction__title'],
 ['m-introduction__body'],
 ['m-introduction__links'],
 ['m-supporter'],
 ['m-supporter__inner'],
 ['m-supporter__content'],
 ['m-supporter__header'],
 ['m-supporter__title'],
 ['m-supporter__body'],
 ['c-button', 'c-button--large'],
 ['m-supporter__branding'],
 ['t-footer'],
 ['t-footer__wrapper'],
 ['o-footer-list'],
 ['o-footer-list__item'],
 ['m-widget'],
 ['m-widget__title'],
 ['m-widget__content'],
 ['vcard'],
 ['org'],
 ['adr', 'street-address'],
 ['adr', 'locality'],
 ['adr', 'postal-code'],
 ['tel'],
 ['u-color--crimson'],
 ['c-button', 'c-button--hollow', 'c-button--light'],
 ['o-socializer', 'o-socializer--inverted'],
 ['m-follow', 'm-follow--inverted'],
 ['c-icon', 'm-follow--inverted'],
 ['m-subscribe', 'm-subscribe--inverted'],
 ['validate'],
 ['c-input', 'c-input--hollow'],
 ['m-meta'],
 ['m-meta__inner'],
 ['m-meta__item'],
 ['m-sharing'],
 ['m-sharing__checkbox', 'show-for-sr'],
 ['m-sharing__toggle'],
 ['m-sharing__list'],
 ['m-sharing__item'],
 ['js-svg', 'c-icon-defs'],
 ['st0'],
 ['st1'],
 ['nofill'],
 ['original']]

In [41]:
import bs4
import pandas as pd
fh=open('Today 52 Week Low BSE_NSE Stocks Companies List – Ticker.html',encoding='utf8')
soup=bs4.BeautifulSoup(fh,'html.parser')

In [42]:
comp=[]
price=[]
daylow=[]

for tag in soup.find_all('td',{'class':'left'}):
    data=tag.text.strip()
    comp.append(data)

for tag in soup.find_all('td',{'class':'Number'}):
    data=tag.text.strip()
    price.append(float(data))

for tag in soup.find_all('span',{'class':'Number'}):
    data=tag.text.strip()
    daylow.append(float(data))
    
df=pd.DataFrame({'Company':comp,
                 'Price in Rs.':price,
                 'Day Low':daylow})
df

                 Company  Price in Rs.  Day Low
0      Rachana Infrastru        125.70   113.80
1         Tirupati Forge          7.80     7.75
2   Sera Investments&Fin         13.01    13.01
3             Viaz Tyres         46.35    45.00
4        Sellwin Traders         13.00    12.01
5          Soni Medicare         19.22    17.40
6          Sicagen India         24.35    24.00
7   Aspira Pathlab&Diagn         24.85    24.80
8          Patspin India         14.10    14.00
9           AG Universal         42.10    42.00
10  Arihant Foundn. &Hsg         39.65    38.50
11  Global Offshore Serv          7.85     7.75
12          GTN Textiles         19.50    19.50
13              GTN Inds         11.95    11.50
14   Vivanza Biosciences          8.33     8.33
15    TECIL Chem & Hydro         21.60    20.70
16   Milgrey Fin.&Invest         16.29    14.81
17        Zodiac-JRD-MKJ         31.95    31.50
18    Kanungo Financiers          5.35     4.85
19        CIL Nova Petro         16.05    15.25
20             Integ.Pro          8.81     8.81
21           Elango Inds          5.55     5.55
22      Voltaire Leasing         11.99    11.54

In [43]:
df.loc[df['Price in Rs.']<20]['Company']

1           Tirupati Forge
2     Sera Investments&Fin
4          Sellwin Traders
5            Soni Medicare
8            Patspin India
11    Global Offshore Serv
12            GTN Textiles
13                GTN Inds
14     Vivanza Biosciences
16     Milgrey Fin.&Invest
18      Kanungo Financiers
19          CIL Nova Petro
20               Integ.Pro
21             Elango Inds
22        Voltaire Leasing
Name: Company, dtype: object

# API : Application Programming Interface
# Key : 9e087baa4cae558ff2c7416885d00a12

## 1. Geocoding API

In [5]:
import requests,json
api_key="9e087baa4cae558ff2c7416885d00a12"
request_url=f"""http://api.openweathermap.org/geo/1.0/direct?q={'Ahmedabad'}&limit=1&appid={api_key}"""
response=requests.get(request_url)
coordinates=response.json()
print(coordinates)
print(json.dumps(coordinates,indent=9,ensure_ascii=False))

[{'name': 'Ahmedabad', 'local_names': {'ta': 'அகமதாபாத்', 'cs': 'Ahmadábád', 'or': 'ଅହମଦାବାଦ', 'oc': 'Ahmadabad', 'ur': 'احمد آباد', 'tt': 'Әхмәтабад', 'ascii': 'Ahmedabad', 'he': 'אחמדאבאד', 'de': 'Ahmedabad', 'feature_name': 'Ahmedabad', 'ar': 'أحمد آباد', 'hi': 'अहमदाबाद', 'gu': 'અમદાવાદ', 'bn': 'আহমেদাবাদ', 'ne': 'अहमदाबाद', 'te': 'అహ్మదాబాద్', 'ru': 'Ахмадабад', 'kn': 'ಅಹ್ಮದಾಬಾದ್', 'ml': 'അഹമ്മദാബാദ്', 'zh': '艾哈迈达巴德', 'en': 'Ahmedabad', 'ja': 'アフマダーバード', 'uk': 'Ахмедабад', 'pa': 'ਅਹਿਮਦਾਬਾਦ', 'mr': 'अहमदाबाद', 'pl': 'Ahmadabad', 'eo': 'Ahmadabado'}, 'lat': 23.0215374, 'lon': 72.5800568, 'country': 'IN', 'state': 'Gujarat'}]
[
         {
                  "name": "Ahmedabad",
                  "local_names": {
                           "ta": "அகமதாபாத்",
                           "cs": "Ahmadábád",
                           "or": "ଅହମଦାବାଦ",
                           "oc": "Ahmadabad",
                           "ur": "احمد آباد",
                           "tt": "Әхмәтабад",
                           "ascii": "Ahmedabad",
                           "he": "אחמדאבאד",
                           "de": "Ahmedabad",
                           "feature_name": "Ahmedabad",
                           "ar": "أحمد آباد",
                           "hi": "अहमदाबाद",
                           "gu": "અમદાવાદ",
                           "bn": "আহমেদাবাদ",
                           "ne": "अहमदाबाद",
                           "te": "అహ్మదాబాద్",
                           "ru": "Ахмадабад",
                           "kn": "ಅಹ್ಮದಾಬಾದ್",
                           "ml": "അഹമ്മദാബാദ്",
                           "zh": "艾哈迈达巴德",
                           "en": "Ahmedabad",
                           "ja": "アフマダーバード",
                           "uk": "Ахмедабад",
                           "pa": "ਅਹਿਮਦਾਬਾਦ",
                           "mr": "अहमदाबाद",
                           "pl": "Ahmadabad",
                           "eo": "Ahmadabado"
                  },
                  "lat": 23.0215374,
                  "lon": 72.5800568,
                  "country": "IN",
                  "state": "Gujarat"
         }
]

In [45]:
lat=coordinates[0]['lat']
long=coordinates[0]['lon']
hname=coordinates[0]['local_names']['hi']
print('latitude:',lat)
print('longitude:',long)
print('hindi name:',hname)

latitude: 23.0215374
longitude: 72.5800568
hindi name: अहमदाबाद

## 2. Current weather data

In [46]:
import requests,json
api_key="9e087baa4cae558ff2c7416885d00a12"
request_url=f"""https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={long}&appid={api_key}"""
response=requests.get(request_url)
coordinates=response.json()
print(coordinates)
print(json.dumps(coordinates,indent=9,ensure_ascii=False))

{'coord': {'lon': 72.5801, 'lat': 23.0215}, 'weather': [{'id': 721, 'main': 'Haze', 'description': 'haze', 'icon': '50d'}], 'base': 'stations', 'main': {'temp': 303.19, 'feels_like': 305.66, 'temp_min': 303.19, 'temp_max': 303.19, 'pressure': 1008, 'humidity': 58, 'sea_level': 1008, 'grnd_level': 1002}, 'visibility': 3000, 'wind': {'speed': 4.12, 'deg': 160}, 'clouds': {'all': 75}, 'dt': 1780111294, 'sys': {'type': 1, 'id': 9049, 'country': 'IN', 'sunrise': 1780100664, 'sunset': 1780149017}, 'timezone': 19800, 'id': 1279233, 'name': 'Ahmedabad', 'cod': 200}
{
         "coord": {
                  "lon": 72.5801,
                  "lat": 23.0215
         },
         "weather": [
                  {
                           "id": 721,
                           "main": "Haze",
                           "description": "haze",
                           "icon": "50d"
                  }
         ],
         "base": "stations",
         "main": {
                  "temp": 303.19,
                  "feels_like": 305.66,
                  "temp_min": 303.19,
                  "temp_max": 303.19,
                  "pressure": 1008,
                  "humidity": 58,
                  "sea_level": 1008,
                  "grnd_level": 1002
         },
         "visibility": 3000,
         "wind": {
                  "speed": 4.12,
                  "deg": 160
         },
         "clouds": {
                  "all": 75
         },
         "dt": 1780111294,
         "sys": {
                  "type": 1,
                  "id": 9049,
                  "country": "IN",
                  "sunrise": 1780100664,
                  "sunset": 1780149017
         },
         "timezone": 19800,
         "id": 1279233,
         "name": "Ahmedabad",
         "cod": 200
}

In [47]:
des=coordinates['weather'][0]['description']
print('description: ',des)
temp=coordinates['main']['temp']
print('Temp: ',temp)
pressure=coordinates['main']['pressure']
print('pressure: ',pressure)
humidity=coordinates['main']['humidity']
print('humidity: ',humidity)
wind_speed=coordinates['wind']['speed']
print('wind speed:',wind_speed)
visibility=coordinates['visibility']
print('visibility:',visibility)

description:  haze
Temp:  303.19
pressure:  1008
humidity:  58
wind speed: 4.12
visibility: 3000

## 3. Air Pollution API concept

In [48]:
import requests,json
api_key="9e087baa4cae558ff2c7416885d00a12"
request_url=f"""http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={long}&appid={api_key}"""
response=requests.get(request_url)
coordinates=response.json()
print(coordinates)
print(json.dumps(coordinates,indent=9,ensure_ascii=False))
# print(json.dumps(coordinates,indent=1))

{'coord': {'lon': 72.5801, 'lat': 23.0215}, 'list': [{'main': {'aqi': 2}, 'components': {'co': 86.26, 'no': 0.25, 'no2': 1.13, 'o3': 30.99, 'so2': 1.1, 'pm2_5': 4.93, 'pm10': 22.49, 'nh3': 0.75}, 'dt': 1780111296}]}
{
         "coord": {
                  "lon": 72.5801,
                  "lat": 23.0215
         },
         "list": [
                  {
                           "main": {
                                    "aqi": 2
                           },
                           "components": {
                                    "co": 86.26,
                                    "no": 0.25,
                                    "no2": 1.13,
                                    "o3": 30.99,
                                    "so2": 1.1,
                                    "pm2_5": 4.93,
                                    "pm10": 22.49,
                                    "nh3": 0.75
                           },
                           "dt": 1780111296
                  }
         ]
}

In [49]:
#fatch the data of aqi and give it rank
aqi=coordinates['list'][0]['main']['aqi']
quality_indices={1:'Good',2:'Fair',3:'Moderate',4:'Poor',5:'Very Poor'}
print('AQI:',aqi)
print('current air quality:',quality_indices[aqi])

AQI: 2
current air quality: Fair

## 4. Forecast air pollution data

In [50]:
import requests,json
api_key="9e087baa4cae558ff2c7416885d00a12"
request_url=f"""http://api.openweathermap.org/data/2.5/air_pollution/forecast?lat={lat}&lon={long}&appid={api_key}"""
response=requests.get(request_url)
coordinates=response.json()
print(coordinates)
print(json.dumps(coordinates,indent=9,ensure_ascii=False))

{'coord': {'lon': 72.5801, 'lat': 23.0215}, 'list': [{'main': {'aqi': 2}, 'components': {'co': 86.26, 'no': 0.25, 'no2': 1.13, 'o3': 30.99, 'so2': 1.1, 'pm2_5': 4.93, 'pm10': 22.49, 'nh3': 0.75}, 'dt': 1780110000}, {'main': {'aqi': 2}, 'components': {'co': 87.59, 'no': 0.23, 'no2': 0.9, 'o3': 37.67, 'so2': 1.06, 'pm2_5': 4.7, 'pm10': 21.98, 'nh3': 0.64}, 'dt': 1780113600}, {'main': {'aqi': 2}, 'components': {'co': 88.32, 'no': 0.18, 'no2': 0.71, 'o3': 45.9, 'so2': 1.02, 'pm2_5': 5.03, 'pm10': 24.11, 'nh3': 0.6}, 'dt': 1780117200}, {'main': {'aqi': 2}, 'components': {'co': 88.65, 'no': 0.15, 'no2': 0.62, 'o3': 52.3, 'so2': 1.06, 'pm2_5': 5.65, 'pm10': 26.31, 'nh3': 0.57}, 'dt': 1780120800}, {'main': {'aqi': 2}, 'components': {'co': 90.01, 'no': 0.13, 'no2': 0.58, 'o3': 58.35, 'so2': 1.08, 'pm2_5': 6.53, 'pm10': 28.84, 'nh3': 0.54}, 'dt': 1780124400}, {'main': {'aqi': 2}, 'components': {'co': 89.63, 'no': 0.11, 'no2': 0.55, 'o3': 61.81, 'so2': 1.02, 'pm2_5': 7.23, 'pm10': 30.76, 'nh3': 0.48}, 'dt': 1780128000}, {'main': {'aqi': 2}, 'components': {'co': 88.72, 'no': 0.1, 'no2': 0.55, 'o3': 62.53, 'so2': 0.99, 'pm2_5': 7.46, 'pm10': 31.23, 'nh3': 0.46}, 'dt': 1780131600}, {'main': {'aqi': 2}, 'components': {'co': 89.55, 'no': 0.1, 'no2': 0.59, 'o3': 63.82, 'so2': 0.97, 'pm2_5': 7.76, 'pm10': 31.76, 'nh3': 0.45}, 'dt': 1780135200}, {'main': {'aqi': 2}, 'components': {'co': 90.23, 'no': 0.12, 'no2': 0.71, 'o3': 63.33, 'so2': 0.96, 'pm2_5': 7.82, 'pm10': 31.79, 'nh3': 0.49}, 'dt': 1780138800}, {'main': {'aqi': 2}, 'components': {'co': 91.28, 'no': 0.12, 'no2': 0.95, 'o3': 60.58, 'so2': 0.97, 'pm2_5': 7.63, 'pm10': 31.69, 'nh3': 0.55}, 'dt': 1780142400}, {'main': {'aqi': 2}, 'components': {'co': 92.54, 'no': 0.09, 'no2': 1.22, 'o3': 56.75, 'so2': 1, 'pm2_5': 7.54, 'pm10': 32.74, 'nh3': 0.61}, 'dt': 1780146000}, {'main': {'aqi': 2}, 'components': {'co': 94.16, 'no': 0.01, 'no2': 1.44, 'o3': 52.56, 'so2': 1.07, 'pm2_5': 7.62, 'pm10': 34.6, 'nh3': 0.69}, 'dt': 1780149600}, {'main': {'aqi': 2}, 'components': {'co': 95.65, 'no': 0, 'no2': 1.48, 'o3': 48.89, 'so2': 1.13, 'pm2_5': 7.76, 'pm10': 35.89, 'nh3': 0.75}, 'dt': 1780153200}, {'main': {'aqi': 2}, 'components': {'co': 94.58, 'no': 0, 'no2': 1.46, 'o3': 44.82, 'so2': 1.15, 'pm2_5': 7.49, 'pm10': 34.8, 'nh3': 0.8}, 'dt': 1780156800}, {'main': {'aqi': 2}, 'components': {'co': 94.74, 'no': 0, 'no2': 1.5, 'o3': 41.81, 'so2': 1.17, 'pm2_5': 7.03, 'pm10': 32.75, 'nh3': 0.88}, 'dt': 1780160400}, {'main': {'aqi': 2}, 'components': {'co': 93.96, 'no': 0, 'no2': 1.53, 'o3': 39.35, 'so2': 1.17, 'pm2_5': 6.45, 'pm10': 30.14, 'nh3': 0.94}, 'dt': 1780164000}, {'main': {'aqi': 2}, 'components': {'co': 91.21, 'no': 0, 'no2': 1.49, 'o3': 37.07, 'so2': 1.14, 'pm2_5': 5.83, 'pm10': 27.3, 'nh3': 1}, 'dt': 1780167600}, {'main': {'aqi': 2}, 'components': {'co': 89.81, 'no': 0, 'no2': 1.44, 'o3': 35.94, 'so2': 1.11, 'pm2_5': 5.43, 'pm10': 25.36, 'nh3': 1.1}, 'dt': 1780171200}, {'main': {'aqi': 2}, 'components': {'co': 89.27, 'no': 0, 'no2': 1.41, 'o3': 35.62, 'so2': 1.1, 'pm2_5': 5.19, 'pm10': 24.24, 'nh3': 1.19}, 'dt': 1780174800}, {'main': {'aqi': 2}, 'components': {'co': 88.73, 'no': 0, 'no2': 1.37, 'o3': 36.26, 'so2': 1.09, 'pm2_5': 5.13, 'pm10': 24.11, 'nh3': 1.22}, 'dt': 1780178400}, {'main': {'aqi': 2}, 'components': {'co': 88.26, 'no': 0, 'no2': 1.33, 'o3': 37.77, 'so2': 1.1, 'pm2_5': 5.2, 'pm10': 24.33, 'nh3': 1.17}, 'dt': 1780182000}, {'main': {'aqi': 2}, 'components': {'co': 87.7, 'no': 0, 'no2': 1.35, 'o3': 38.21, 'so2': 1.13, 'pm2_5': 5, 'pm10': 23.12, 'nh3': 1.12}, 'dt': 1780185600}, {'main': {'aqi': 2}, 'components': {'co': 87.67, 'no': 0, 'no2': 1.42, 'o3': 37.63, 'so2': 1.15, 'pm2_5': 4.66, 'pm10': 21.43, 'nh3': 1.07}, 'dt': 1780189200}, {'main': {'aqi': 2}, 'components': {'co': 89.07, 'no': 0.09, 'no2': 1.47, 'o3': 37.55, 'so2': 1.18, 'pm2_5': 4.36, 'pm10': 20.12, 'nh3': 1.02}, 'dt': 1780192800}, {'main': {'aqi': 1}, 'components': {'co': 89.85, 'no': 0.25, 'no2': 1.23, 'o3': 40.38, 'so2': 1.16, 'pm2_5': 4.13, 'pm10': 19.14, 'nh3': 0.89}, 'dt': 1780196400}, {'main': {'aqi': 1}, 'components': {'co': 89.56, 'no': 0.22, 'no2': 0.89, 'o3': 47.83, 'so2': 1.05, 'pm2_5': 4.22, 'pm10': 19.68, 'nh3': 0.72}, 'dt': 1780200000}, {'main': {'aqi': 2}, 'components': {'co': 89.31, 'no': 0.16, 'no2': 0.7, 'o3': 54.73, 'so2': 1.01, 'pm2_5': 4.73, 'pm10': 21.59, 'nh3': 0.66}, 'dt': 1780203600}, {'main': {'aqi': 2}, 'components': {'co': 88.96, 'no': 0.14, 'no2': 0.61, 'o3': 59.32, 'so2': 1.05, 'pm2_5': 5.4, 'pm10': 23.22, 'nh3': 0.64}, 'dt': 1780207200}, {'main': {'aqi': 2}, 'components': {'co': 90.01, 'no': 0.12, 'no2': 0.57, 'o3': 63.93, 'so2': 1.05, 'pm2_5': 6.12, 'pm10': 24.93, 'nh3': 0.61}, 'dt': 1780210800}, {'main': {'aqi': 2}, 'components': {'co': 89.73, 'no': 0.1, 'no2': 0.54, 'o3': 66.92, 'so2': 0.99, 'pm2_5': 6.66, 'pm10': 26.39, 'nh3': 0.57}, 'dt': 1780214400}, {'main': {'aqi': 2}, 'components': {'co': 89.32, 'no': 0.1, 'no2': 0.55, 'o3': 67.49, 'so2': 0.98, 'pm2_5': 6.91, 'pm10': 26.85, 'nh3': 0.56}, 'dt': 1780218000}, {'main': {'aqi': 2}, 'components': {'co': 90.66, 'no': 0.1, 'no2': 0.59, 'o3': 69.73, 'so2': 0.99, 'pm2_5': 7.09, 'pm10': 27.08, 'nh3': 0.57}, 'dt': 1780221600}, {'main': {'aqi': 2}, 'components': {'co': 91.73, 'no': 0.1, 'no2': 0.72, 'o3': 71.27, 'so2': 1.01, 'pm2_5': 7.06, 'pm10': 26.69, 'nh3': 0.58}, 'dt': 1780225200}, {'main': {'aqi': 2}, 'components': {'co': 93.17, 'no': 0.09, 'no2': 0.96, 'o3': 70.64, 'so2': 1.09, 'pm2_5': 6.91, 'pm10': 26.09, 'nh3': 0.62}, 'dt': 1780228800}, {'main': {'aqi': 2}, 'components': {'co': 96.34, 'no': 0.07, 'no2': 1.46, 'o3': 67.58, 'so2': 1.24, 'pm2_5': 6.77, 'pm10': 25.8, 'nh3': 0.76}, 'dt': 1780232400}, {'main': {'aqi': 2}, 'components': {'co': 100.78, 'no': 0.01, 'no2': 2.04, 'o3': 63.16, 'so2': 1.44, 'pm2_5': 6.77, 'pm10': 26.39, 'nh3': 1}, 'dt': 1780236000}, {'main': {'aqi': 2}, 'components': {'co': 103.65, 'no': 0, 'no2': 2.29, 'o3': 58.73, 'so2': 1.61, 'pm2_5': 6.85, 'pm10': 27.49, 'nh3': 1.21}, 'dt': 1780239600}, {'main': {'aqi': 2}, 'components': {'co': 103.57, 'no': 0, 'no2': 2.38, 'o3': 53.06, 'so2': 1.74, 'pm2_5': 6.87, 'pm10': 28.35, 'nh3': 1.35}, 'dt': 1780243200}, {'main': {'aqi': 2}, 'components': {'co': 104.32, 'no': 0, 'no2': 2.52, 'o3': 48.57, 'so2': 1.92, 'pm2_5': 7.13, 'pm10': 30.03, 'nh3': 1.48}, 'dt': 1780246800}, {'main': {'aqi': 2}, 'components': {'co': 103.12, 'no': 0, 'no2': 2.52, 'o3': 44.79, 'so2': 2.07, 'pm2_5': 7.41, 'pm10': 31.76, 'nh3': 1.48}, 'dt': 1780250400}, {'main': {'aqi': 2}, 'components': {'co': 98.86, 'no': 0, 'no2': 2.27, 'o3': 41.32, 'so2': 2.11, 'pm2_5': 7.52, 'pm10': 33.04, 'nh3': 1.32}, 'dt': 1780254000}, {'main': {'aqi': 2}, 'components': {'co': 97.19, 'no': 0, 'no2': 2.12, 'o3': 37.86, 'so2': 1.97, 'pm2_5': 7.49, 'pm10': 33.42, 'nh3': 1.34}, 'dt': 1780257600}, {'main': {'aqi': 2}, 'components': {'co': 95.49, 'no': 0, 'no2': 1.95, 'o3': 35.56, 'so2': 1.76, 'pm2_5': 7.43, 'pm10': 33.57, 'nh3': 1.36}, 'dt': 1780261200}, {'main': {'aqi': 2}, 'components': {'co': 93.22, 'no': 0, 'no2': 1.79, 'o3': 33.78, 'so2': 1.55, 'pm2_5': 7.34, 'pm10': 33.4, 'nh3': 1.37}, 'dt': 1780264800}, {'main': {'aqi': 2}, 'components': {'co': 92.51, 'no': 0, 'no2': 1.72, 'o3': 32.63, 'so2': 1.39, 'pm2_5': 7.35, 'pm10': 33.59, 'nh3': 1.42}, 'dt': 1780268400}, {'main': {'aqi': 2}, 'components': {'co': 92.77, 'no': 0, 'no2': 1.76, 'o3': 31.88, 'so2': 1.32, 'pm2_5': 7.42, 'pm10': 34.1, 'nh3': 1.46}, 'dt': 1780272000}, {'main': {'aqi': 2}, 'components': {'co': 95, 'no': 0, 'no2': 2.05, 'o3': 31.25, 'so2': 1.35, 'pm2_5': 7.53, 'pm10': 34.97, 'nh3': 4.05}, 'dt': 1780275600}, {'main': {'aqi': 2}, 'components': {'co': 99.22, 'no': 0.17, 'no2': 2.37, 'o3': 31.44, 'so2': 1.51, 'pm2_5': 7.65, 'pm10': 35.92, 'nh3': 5.38}, 'dt': 1780279200}, {'main': {'aqi': 2}, 'components': {'co': 100.29, 'no': 0.53, 'no2': 2.07, 'o3': 34.42, 'so2': 1.73, 'pm2_5': 7.61, 'pm10': 36.11, 'nh3': 5.22}, 'dt': 1780282800}, {'main': {'aqi': 2}, 'components': {'co': 95.89, 'no': 0.43, 'no2': 1.45, 'o3': 43.49, 'so2': 1.73, 'pm2_5': 7.4, 'pm10': 35.49, 'nh3': 4.2}, 'dt': 1780286400}, {'main': {'aqi': 2}, 'components': {'co': 94.74, 'no': 0.28, 'no2': 1.08, 'o3': 52.78, 'so2': 1.66, 'pm2_5': 7.65, 'pm10': 34.55, 'nh3': 4.25}, 'dt': 1780290000}, {'main': {'aqi': 2}, 'components': {'co': 94.98, 'no': 0.21, 'no2': 0.9, 'o3': 60.83, 'so2': 1.65, 'pm2_5': 8.55, 'pm10': 34.63, 'nh3': 4.6}, 'dt': 1780293600}, {'main': {'aqi': 2}, 'components': {'co': 95.5, 'no': 0.16, 'no2': 0.76, 'o3': 68.46, 'so2': 1.52, 'pm2_5': 9.39, 'pm10': 35.76, 'nh3': 4.56}, 'dt': 1780297200}, {'main': {'aqi': 2}, 'components': {'co': 94.61, 'no': 0.13, 'no2': 0.7, 'o3': 72.6, 'so2': 1.37, 'pm2_5': 9.79, 'pm10': 36.8, 'nh3': 4.32}, 'dt': 1780300800}, {'main': {'aqi': 2}, 'components': {'co': 94.51, 'no': 0.12, 'no2': 0.72, 'o3': 74.36, 'so2': 1.38, 'pm2_5': 10.07, 'pm10': 37.53, 'nh3': 4.38}, 'dt': 1780304400}, {'main': {'aqi': 2}, 'components': {'co': 97.16, 'no': 0.12, 'no2': 0.86, 'o3': 76.6, 'so2': 1.42, 'pm2_5': 10.45, 'pm10': 38.51, 'nh3': 4.83}, 'dt': 1780308000}, {'main': {'aqi': 2}, 'components': {'co': 101.33, 'no': 0.13, 'no2': 1.2, 'o3': 77.96, 'so2': 1.48, 'pm2_5': 10.78, 'pm10': 38.81, 'nh3': 5.65}, 'dt': 1780311600}, {'main': {'aqi': 2}, 'components': {'co': 106.6, 'no': 0.14, 'no2': 1.77, 'o3': 77.66, 'so2': 1.65, 'pm2_5': 10.88, 'pm10': 38.29, 'nh3': 6.37}, 'dt': 1780315200}, {'main': {'aqi': 2}, 'components': {'co': 110.63, 'no': 0.09, 'no2': 2.37, 'o3': 75.02, 'so2': 1.86, 'pm2_5': 10.61, 'pm10': 37.17, 'nh3': 6.91}, 'dt': 1780318800}, {'main': {'aqi': 2}, 'components': {'co': 113.58, 'no': 0.01, 'no2': 2.78, 'o3': 71.09, 'so2': 2.03, 'pm2_5': 10.06, 'pm10': 35.88, 'nh3': 7.48}, 'dt': 1780322400}, {'main': {'aqi': 2}, 'components': {'co': 114.97, 'no': 0, 'no2': 2.91, 'o3': 66.12, 'so2': 2.09, 'pm2_5': 9.28, 'pm10': 34.08, 'nh3': 8.04}, 'dt': 1780326000}, {'main': {'aqi': 2}, 'components': {'co': 113.69, 'no': 0, 'no2': 2.93, 'o3': 59.43, 'so2': 2.1, 'pm2_5': 8.36, 'pm10': 31.63, 'nh3': 8.56}, 'dt': 1780329600}, {'main': {'aqi': 2}, 'components': {'co': 114.49, 'no': 0, 'no2': 3.08, 'o3': 54.39, 'so2': 2.17, 'pm2_5': 7.95, 'pm10': 30.69, 'nh3': 9.55}, 'dt': 1780333200}, {'main': {'aqi': 2}, 'components': {'co': 114.21, 'no': 0, 'no2': 3.23, 'o3': 50.87, 'so2': 2.29, 'pm2_5': 7.95, 'pm10': 30.92, 'nh3': 10.57}, 'dt': 1780336800}, {'main': {'aqi': 2}, 'components': {'co': 110.16, 'no': 0, 'no2': 3.14, 'o3': 47.86, 'so2': 2.41, 'pm2_5': 8.06, 'pm10': 31.36, 'nh3': 10.91}, 'dt': 1780340400}, {'main': {'aqi': 2}, 'components': {'co': 106.87, 'no': 0, 'no2': 2.98, 'o3': 44.75, 'so2': 2.55, 'pm2_5': 8.13, 'pm10': 31.54, 'nh3': 11.17}, 'dt': 1780344000}, {'main': {'aqi': 2}, 'components': {'co': 105.25, 'no': 0, 'no2': 2.86, 'o3': 41.76, 'so2': 2.59, 'pm2_5': 8.15, 'pm10': 31.34, 'nh3': 11.64}, 'dt': 1780347600}, {'main': {'aqi': 2}, 'components': {'co': 103.81, 'no': 0, 'no2': 2.7, 'o3': 39.4, 'so2': 2.43, 'pm2_5': 8.09, 'pm10': 30.88, 'nh3': 12.1}, 'dt': 1780351200}, {'main': {'aqi': 2}, 'components': {'co': 103.18, 'no': 0, 'no2': 2.57, 'o3': 37.98, 'so2': 2.17, 'pm2_5': 8.11, 'pm10': 30.79, 'nh3': 12.45}, 'dt': 1780354800}, {'main': {'aqi': 2}, 'components': {'co': 102.9, 'no': 0, 'no2': 2.52, 'o3': 36.89, 'so2': 1.94, 'pm2_5': 8.11, 'pm10': 30.95, 'nh3': 12.36}, 'dt': 1780358400}, {'main': {'aqi': 2}, 'components': {'co': 103.18, 'no': 0, 'no2': 2.64, 'o3': 35.67, 'so2': 1.82, 'pm2_5': 8.1, 'pm10': 31.27, 'nh3': 12.01}, 'dt': 1780362000}, {'main': {'aqi': 2}, 'components': {'co': 105.94, 'no': 0.18, 'no2': 2.81, 'o3': 34.85, 'so2': 1.88, 'pm2_5': 8.15, 'pm10': 32.05, 'nh3': 11.65}, 'dt': 1780365600}, {'main': {'aqi': 2}, 'components': {'co': 107.4, 'no': 0.6, 'no2': 2.43, 'o3': 36.51, 'so2': 2, 'pm2_5': 8.2, 'pm10': 32.74, 'nh3': 10.82}, 'dt': 1780369200}, {'main': {'aqi': 2}, 'components': {'co': 102.91, 'no': 0.48, 'no2': 1.73, 'o3': 46.36, 'so2': 1.83, 'pm2_5': 7.89, 'pm10': 31.5, 'nh3': 8.34}, 'dt': 1780372800}, {'main': {'aqi': 2}, 'components': {'co': 100.32, 'no': 0.27, 'no2': 1.23, 'o3': 58.84, 'so2': 1.63, 'pm2_5': 7.94, 'pm10': 30.25, 'nh3': 6.88}, 'dt': 1780376400}, {'main': {'aqi': 2}, 'components': {'co': 99.18, 'no': 0.18, 'no2': 1, 'o3': 67.35, 'so2': 1.57, 'pm2_5': 8.5, 'pm10': 30.3, 'nh3': 6.23}, 'dt': 1780380000}, {'main': {'aqi': 2}, 'components': {'co': 99.6, 'no': 0.14, 'no2': 0.87, 'o3': 75.01, 'so2': 1.48, 'pm2_5': 8.98, 'pm10': 30.54, 'nh3': 5.6}, 'dt': 1780383600}, {'main': {'aqi': 2}, 'components': {'co': 98.93, 'no': 0.12, 'no2': 0.77, 'o3': 79.54, 'so2': 1.34, 'pm2_5': 8.99, 'pm10': 29.73, 'nh3': 4.95}, 'dt': 1780387200}, {'main': {'aqi': 2}, 'components': {'co': 98.7, 'no': 0.11, 'no2': 0.76, 'o3': 81.56, 'so2': 1.29, 'pm2_5': 9, 'pm10': 29.18, 'nh3': 4.67}, 'dt': 1780390800}, {'main': {'aqi': 2}, 'components': {'co': 100.57, 'no': 0.12, 'no2': 0.83, 'o3': 83.98, 'so2': 1.29, 'pm2_5': 9.11, 'pm10': 28.86, 'nh3': 4.71}, 'dt': 1780394400}, {'main': {'aqi': 2}, 'components': {'co': 103.14, 'no': 0.14, 'no2': 1.1, 'o3': 84.8, 'so2': 1.32, 'pm2_5': 9.1, 'pm10': 28.39, 'nh3': 5.18}, 'dt': 1780398000}, {'main': {'aqi': 2}, 'components': {'co': 106.28, 'no': 0.15, 'no2': 1.55, 'o3': 83.36, 'so2': 1.39, 'pm2_5': 8.9, 'pm10': 27.93, 'nh3': 5.69}, 'dt': 1780401600}, {'main': {'aqi': 2}, 'components': {'co': 109.72, 'no': 0.11, 'no2': 2.14, 'o3': 79, 'so2': 1.51, 'pm2_5': 8.68, 'pm10': 28.37, 'nh3': 6.37}, 'dt': 1780405200}, {'main': {'aqi': 2}, 'components': {'co': 113.66, 'no': 0.02, 'no2': 2.77, 'o3': 71.86, 'so2': 1.74, 'pm2_5': 8.61, 'pm10': 29.95, 'nh3': 7.34}, 'dt': 1780408800}, {'main': {'aqi': 2}, 'components': {'co': 116.47, 'no': 0, 'no2': 3.14, 'o3': 63.62, 'so2': 2.03, 'pm2_5': 8.65, 'pm10': 32.01, 'nh3': 8.28}, 'dt': 1780412400}, {'main': {'aqi': 2}, 'components': {'co': 115.86, 'no': 0, 'no2': 3.31, 'o3': 55.14, 'so2': 2.29, 'pm2_5': 8.62, 'pm10': 33.57, 'nh3': 8.88}, 'dt': 1780416000}, {'main': {'aqi': 2}, 'components': {'co': 116.14, 'no': 0, 'no2': 3.48, 'o3': 49.69, 'so2': 2.49, 'pm2_5': 8.73, 'pm10': 34.92, 'nh3': 9.6}, 'dt': 1780419600}, {'main': {'aqi': 2}, 'components': {'co': 115.44, 'no': 0, 'no2': 3.59, 'o3': 46.29, 'so2': 2.6, 'pm2_5': 8.79, 'pm10': 35.31, 'nh3': 10.41}, 'dt': 1780423200}, {'main': {'aqi': 2}, 'components': {'co': 113.95, 'no': 0, 'no2': 3.66, 'o3': 42.86, 'so2': 2.69, 'pm2_5': 8.52, 'pm10': 33.34, 'nh3': 11.63}, 'dt': 1780426800}, {'main': {'aqi': 2}, 'components': {'co': 116.27, 'no': 0, 'no2': 3.74, 'o3': 40.13, 'so2': 2.79, 'pm2_5': 8.24, 'pm10': 30.16, 'nh3': 13.09}, 'dt': 1780430400}, {'main': {'aqi': 2}, 'components': {'co': 119.38, 'no': 0, 'no2': 3.72, 'o3': 38.5, 'so2': 2.83, 'pm2_5': 8.01, 'pm10': 26.96, 'nh3': 13.14}, 'dt': 1780434000}, {'main': {'aqi': 2}, 'components': {'co': 119.75, 'no': 0, 'no2': 3.46, 'o3': 37.47, 'so2': 2.62, 'pm2_5': 7.79, 'pm10': 24.17, 'nh3': 12.66}, 'dt': 1780437600}, {'main': {'aqi': 2}, 'components': {'co': 118.39, 'no': 0, 'no2': 3.07, 'o3': 37.55, 'so2': 2.16, 'pm2_5': 7.69, 'pm10': 22.97, 'nh3': 10.98}, 'dt': 1780441200}, {'main': {'aqi': 2}, 'components': {'co': 114.97, 'no': 0, 'no2': 2.75, 'o3': 38.15, 'so2': 1.75, 'pm2_5': 7.43, 'pm10': 21.82, 'nh3': 9.43}, 'dt': 1780444800}, {'main': {'aqi': 2}, 'components': {'co': 112.85, 'no': 0, 'no2': 2.82, 'o3': 38.49, 'so2': 1.54, 'pm2_5': 7.27, 'pm10': 22.13, 'nh3': 8.76}, 'dt': 1780448400}, {'main': {'aqi': 2}, 'components': {'co': 116.08, 'no': 0.17, 'no2': 3.3, 'o3': 37.19, 'so2': 1.63, 'pm2_5': 7.45, 'pm10': 24.53, 'nh3': 9.65}, 'dt': 1780452000}]}
{
         "coord": {
                  "lon": 72.5801,
                  "lat": 23.0215
         },
         "list": [
                  {
                           "main": {
                                    "aqi": 2
                           },
                           "components": {
                                    "co": 86.26,
                                    "no": 0.25,
                                    "no2": 1.13,
                                    "o3": 30.99,
                                    "so2": 1.1,
                                    "pm2_5": 4.93,
                                    "pm10": 22.49,
                                    "nh3": 0.75
                           },
                           "dt": 1780110000
                  },
                  {
                           "main": {
                                    "aqi": 2
                           },
                           "components": {
                                    "co": 87.59,
                                    "no": 0.23,
                                    "no2": 0.9,
                                    "o3": 37.67,
                                    "so2": 1.06,
                                    "pm2_5": 4.7,
                                    "pm10": 21.98,
                                    "nh3": 0.64
                           },
                           "dt": 1780113600
                  },
                  {
                           "main": {
                                    "aqi": 2
                           },
                           "components": {
                                    "co": 88.32,
                                    "no": 0.18,
                                    "no2": 0.71,
                                    "o3": 45.9,
                                    "so2": 1.02,
                                    "pm2_5": 5.03,
                                    "pm10": 24.11,
                                    "nh3": 0.6
                           },
                           "dt": 1780117200
                  },
                  {
                           "main": {
                                    "aqi": 2
                           },
                           "components": {
                                    "co": 88.65,
                                    "no": 0.15,
                                    "no2": 0.62,
                                    "o3": 52.3,
                                    "so2": 1.06,
                                    "pm2_5": 5.65,
                                    "pm10": 26.31,
                                    "nh3": 0.57
                           },
                           "dt": 1780120800
                  },
                  {
                           "main": {
                                    "aqi": 2
                           },
                           "components": {
                                    "co": 90.01,
                                    "no": 0.13,
                                    "no2": 0.58,
                                    "o3": 58.35,
                                    "so2": 1.08,
                                    "pm2_5": 6.53,
                                    "pm10": 28.84,
                                    "nh3": 0.54
                           },
                           "dt": 1780124400
                  },
                  {
                           "main": {
                                    "aqi": 2
                           },
                           "components": {
                                    "co": 89.63,
                                    "no": 0.11,
                                    "no2": 0.55,
                                    "o3": 61.81,
                                    "so2": 1.02,
                                    "pm2_5": 7.23,
                                    "pm10": 30.76,
                                    "nh3": 0.48
                           },
                           "dt": 1780128000
                  },
                  {
                           "main": {
                                    "aqi": 2
                           },
                           "components": {
                                    "co": 88.72,
                                    "no": 0.1,
                                    "no2": 0.55,

In [51]:
import pandas as pd
D={'date_time':[],'co':[],'no':[],'no2':[],'o3':[],'so2':[],'pm2_5':[],'pm10':[],'nh3':[]}
for i in coordinates['list']:
    D['date_time'].append(i['dt'])
    D['co'].append(i['components']['co'])
    D['no'].append(i['components']['no'])
    D['no2'].append(i['components']['no2'])
    D['o3'].append(i['components']['o3'])
    D['so2'].append(i['components']['so2'])
    D['pm2_5'].append(i['components']['pm2_5'])
    D['pm10'].append(i['components']['pm10'])
    D['nh3'].append(i['components']['nh3'])
df=pd.DataFrame(D)
df

     date_time      co    no   no2     o3   so2  pm2_5   pm10    nh3
0   1780110000   86.26  0.25  1.13  30.99  1.10   4.93  22.49   0.75
1   1780113600   87.59  0.23  0.90  37.67  1.06   4.70  21.98   0.64
2   1780117200   88.32  0.18  0.71  45.90  1.02   5.03  24.11   0.60
3   1780120800   88.65  0.15  0.62  52.30  1.06   5.65  26.31   0.57
4   1780124400   90.01  0.13  0.58  58.35  1.08   6.53  28.84   0.54
..         ...     ...   ...   ...    ...   ...    ...    ...    ...
91  1780437600  119.75  0.00  3.46  37.47  2.62   7.79  24.17  12.66
92  1780441200  118.39  0.00  3.07  37.55  2.16   7.69  22.97  10.98
93  1780444800  114.97  0.00  2.75  38.15  1.75   7.43  21.82   9.43
94  1780448400  112.85  0.00  2.82  38.49  1.54   7.27  22.13   8.76
95  1780452000  116.08  0.17  3.30  37.19  1.63   7.45  24.53   9.65

[96 rows x 9 columns]

## Code to Generate Air pollution History Data

In [52]:
import requests,json
api_key="9e087baa4cae558ff2c7416885d00a12"
start=1606488670
end=1606747870
request_url=f"""http://api.openweathermap.org/data/2.5/air_pollution/history?lat={lat}&lon={long}&start={start}&end={end}&appid={api_key}"""
response=requests.get(request_url)
coordinates=response.json()
print(coordinates)
print(json.dumps(coordinates,indent=9,ensure_ascii=False))

{'coord': {'lon': 72.5801, 'lat': 23.0215}, 'list': [{'main': {'aqi': 5}, 'components': {'co': 747.68, 'no': 0, 'no2': 21.59, 'o3': 97.28, 'so2': 23.84, 'pm2_5': 70.46, 'pm10': 81.04, 'nh3': 14.82}, 'dt': 1606489200}, {'main': {'aqi': 5}, 'components': {'co': 734.33, 'no': 0, 'no2': 18.17, 'o3': 100.14, 'so2': 21.22, 'pm2_5': 72.29, 'pm10': 82.97, 'nh3': 14.57}, 'dt': 1606492800}, {'main': {'aqi': 5}, 'components': {'co': 707.63, 'no': 0, 'no2': 15.42, 'o3': 105.86, 'so2': 19.31, 'pm2_5': 77.1, 'pm10': 87.09, 'nh3': 13.3}, 'dt': 1606496400}, {'main': {'aqi': 5}, 'components': {'co': 640.87, 'no': 0, 'no2': 12.51, 'o3': 110.15, 'so2': 17.88, 'pm2_5': 77.92, 'pm10': 86.42, 'nh3': 11.02}, 'dt': 1606500000}, {'main': {'aqi': 5}, 'components': {'co': 560.76, 'no': 0, 'no2': 9.68, 'o3': 113.01, 'so2': 17.17, 'pm2_5': 73.69, 'pm10': 80.47, 'nh3': 9.12}, 'dt': 1606503600}, {'main': {'aqi': 5}, 'components': {'co': 520.71, 'no': 0, 'no2': 7.37, 'o3': 113.01, 'so2': 15.14, 'pm2_5': 69.33, 'pm10': 75.08, 'nh3': 8.87}, 'dt': 1606507200}, {'main': {'aqi': 5}, 'components': {'co': 494, 'no': 0, 'no2': 6.68, 'o3': 110.15, 'so2': 14.31, 'pm2_5': 65.34, 'pm10': 70.52, 'nh3': 9.12}, 'dt': 1606510800}, {'main': {'aqi': 5}, 'components': {'co': 487.33, 'no': 0, 'no2': 6.77, 'o3': 105.86, 'so2': 13.83, 'pm2_5': 61.91, 'pm10': 66.67, 'nh3': 9.63}, 'dt': 1606514400}, {'main': {'aqi': 5}, 'components': {'co': 480.65, 'no': 0, 'no2': 6.86, 'o3': 103, 'so2': 13.35, 'pm2_5': 58.87, 'pm10': 63.33, 'nh3': 9.88}, 'dt': 1606518000}, {'main': {'aqi': 5}, 'components': {'co': 487.33, 'no': 0, 'no2': 7.28, 'o3': 98.71, 'so2': 13.23, 'pm2_5': 57.97, 'pm10': 62.2, 'nh3': 10.13}, 'dt': 1606521600}, {'main': {'aqi': 5}, 'components': {'co': 520.71, 'no': 0, 'no2': 8.91, 'o3': 94.41, 'so2': 13.71, 'pm2_5': 58.74, 'pm10': 63.26, 'nh3': 10.77}, 'dt': 1606525200}, {'main': {'aqi': 5}, 'components': {'co': 594.14, 'no': 0, 'no2': 12.85, 'o3': 87.26, 'so2': 16.21, 'pm2_5': 61.64, 'pm10': 67.22, 'nh3': 11.78}, 'dt': 1606528800}, {'main': {'aqi': 5}, 'components': {'co': 620.84, 'no': 0.36, 'no2': 15.77, 'o3': 84.4, 'so2': 19.07, 'pm2_5': 62.36, 'pm10': 68.76, 'nh3': 11.91}, 'dt': 1606532400}, {'main': {'aqi': 5}, 'components': {'co': 594.14, 'no': 1.36, 'no2': 13.2, 'o3': 90.12, 'so2': 20.74, 'pm2_5': 60.3, 'pm10': 66.88, 'nh3': 11.02}, 'dt': 1606536000}, {'main': {'aqi': 5}, 'components': {'co': 567.44, 'no': 1.75, 'no2': 10.97, 'o3': 100.14, 'so2': 22.89, 'pm2_5': 58.04, 'pm10': 64.63, 'nh3': 10.51}, 'dt': 1606539600}, {'main': {'aqi': 5}, 'components': {'co': 540.73, 'no': 1.59, 'no2': 9.51, 'o3': 115.87, 'so2': 25.51, 'pm2_5': 56.65, 'pm10': 63, 'nh3': 9.88}, 'dt': 1606543200}, {'main': {'aqi': 5}, 'components': {'co': 453.95, 'no': 1.12, 'no2': 7.54, 'o3': 137.33, 'so2': 27.66, 'pm2_5': 52.05, 'pm10': 56.79, 'nh3': 6.14}, 'dt': 1606546800}, {'main': {'aqi': 5}, 'components': {'co': 433.92, 'no': 0.96, 'no2': 6.94, 'o3': 144.48, 'so2': 27.18, 'pm2_5': 50.95, 'pm10': 55.27, 'nh3': 4.94}, 'dt': 1606550400}, {'main': {'aqi': 5}, 'components': {'co': 420.57, 'no': 0.86, 'no2': 6.94, 'o3': 147.34, 'so2': 26.23, 'pm2_5': 51.21, 'pm10': 55.53, 'nh3': 4.43}, 'dt': 1606554000}, {'main': {'aqi': 5}, 'components': {'co': 507.36, 'no': 1.26, 'no2': 12, 'o3': 141.62, 'so2': 26.94, 'pm2_5': 55.2, 'pm10': 60.21, 'nh3': 6.65}, 'dt': 1606557600}, {'main': {'aqi': 5}, 'components': {'co': 634.19, 'no': 1.37, 'no2': 19.36, 'o3': 128.75, 'so2': 26.46, 'pm2_5': 60.52, 'pm10': 67.15, 'nh3': 10.01}, 'dt': 1606561200}, {'main': {'aqi': 5}, 'components': {'co': 741.01, 'no': 0.57, 'no2': 28.1, 'o3': 107.29, 'so2': 25.99, 'pm2_5': 63.52, 'pm10': 71.79, 'nh3': 12.67}, 'dt': 1606564800}, {'main': {'aqi': 5}, 'components': {'co': 814.44, 'no': 0.01, 'no2': 30.16, 'o3': 90.84, 'so2': 24.8, 'pm2_5': 65.39, 'pm10': 75.05, 'nh3': 14.82}, 'dt': 1606568400}, {'main': {'aqi': 5}, 'components': {'co': 847.82, 'no': 0, 'no2': 27.08, 'o3': 85.83, 'so2': 24.08, 'pm2_5': 67.13, 'pm10': 78.18, 'nh3': 16.72}, 'dt': 1606572000}, {'main': {'aqi': 5}, 'components': {'co': 847.82, 'no': 0, 'no2': 23.65, 'o3': 84.4, 'so2': 23.6, 'pm2_5': 67.6, 'pm10': 79.35, 'nh3': 17.73}, 'dt': 1606575600}, {'main': {'aqi': 5}, 'components': {'co': 787.74, 'no': 0, 'no2': 19.02, 'o3': 87.98, 'so2': 21.22, 'pm2_5': 64.12, 'pm10': 75.64, 'nh3': 16.72}, 'dt': 1606579200}, {'main': {'aqi': 5}, 'components': {'co': 714.3, 'no': 0, 'no2': 16.28, 'o3': 91.55, 'so2': 18.84, 'pm2_5': 60.24, 'pm10': 70.83, 'nh3': 15.45}, 'dt': 1606582800}, {'main': {'aqi': 5}, 'components': {'co': 607.49, 'no': 0, 'no2': 13.54, 'o3': 94.41, 'so2': 15.97, 'pm2_5': 54.08, 'pm10': 62.81, 'nh3': 13.3}, 'dt': 1606586400}, {'main': {'aqi': 4}, 'components': {'co': 514.03, 'no': 0, 'no2': 10.63, 'o3': 97.28, 'so2': 13.59, 'pm2_5': 48.09, 'pm10': 54.55, 'nh3': 11.65}, 'dt': 1606590000}, {'main': {'aqi': 4}, 'components': {'co': 487.33, 'no': 0, 'no2': 9, 'o3': 95.84, 'so2': 12.52, 'pm2_5': 45.69, 'pm10': 50.93, 'nh3': 11.65}, 'dt': 1606593600}, {'main': {'aqi': 4}, 'components': {'co': 473.98, 'no': 0, 'no2': 8.05, 'o3': 91.55, 'so2': 11.8, 'pm2_5': 43.77, 'pm10': 48.43, 'nh3': 11.78}, 'dt': 1606597200}, {'main': {'aqi': 4}, 'components': {'co': 467.3, 'no': 0, 'no2': 7.8, 'o3': 88.69, 'so2': 11.8, 'pm2_5': 42.8, 'pm10': 47.23, 'nh3': 12.16}, 'dt': 1606600800}, {'main': {'aqi': 4}, 'components': {'co': 460.63, 'no': 0, 'no2': 7.71, 'o3': 87.26, 'so2': 12.4, 'pm2_5': 42.74, 'pm10': 47.05, 'nh3': 12.29}, 'dt': 1606604400}, {'main': {'aqi': 4}, 'components': {'co': 467.3, 'no': 0, 'no2': 7.88, 'o3': 87.26, 'so2': 13.35, 'pm2_5': 43.16, 'pm10': 47.36, 'nh3': 12.16}, 'dt': 1606608000}, {'main': {'aqi': 4}, 'components': {'co': 494, 'no': 0, 'no2': 9.34, 'o3': 87.26, 'so2': 15.02, 'pm2_5': 44.69, 'pm10': 49.18, 'nh3': 12.54}, 'dt': 1606611600}, {'main': {'aqi': 4}, 'components': {'co': 574.11, 'no': 0, 'no2': 13.37, 'o3': 81.54, 'so2': 18.36, 'pm2_5': 48.08, 'pm10': 53.67, 'nh3': 13.55}, 'dt': 1606615200}, {'main': {'aqi': 5}, 'components': {'co': 620.84, 'no': 0.39, 'no2': 16.79, 'o3': 75.82, 'so2': 21.46, 'pm2_5': 50.37, 'pm10': 56.9, 'nh3': 13.81}, 'dt': 1606618800}, {'main': {'aqi': 4}, 'components': {'co': 594.14, 'no': 1.55, 'no2': 14.4, 'o3': 78.68, 'so2': 22.89, 'pm2_5': 49.65, 'pm10': 56.36, 'nh3': 13.3}, 'dt': 1606622400}, {'main': {'aqi': 4}, 'components': {'co': 567.44, 'no': 2.04, 'no2': 12.17, 'o3': 87.98, 'so2': 25.03, 'pm2_5': 48.67, 'pm10': 55.28, 'nh3': 13.05}, 'dt': 1606626000}, {'main': {'aqi': 5}, 'components': {'co': 534.06, 'no': 1.9, 'no2': 10.8, 'o3': 103, 'so2': 27.66, 'pm2_5': 50.13, 'pm10': 56.56, 'nh3': 12.67}, 'dt': 1606629600}, {'main': {'aqi': 5}, 'components': {'co': 460.63, 'no': 1.4, 'no2': 8.82, 'o3': 121.59, 'so2': 28.37, 'pm2_5': 59.87, 'pm10': 65.34, 'nh3': 8.61}, 'dt': 1606633200}, {'main': {'aqi': 5}, 'components': {'co': 433.92, 'no': 1.19, 'no2': 8.31, 'o3': 133.04, 'so2': 29.33, 'pm2_5': 65.74, 'pm10': 71.07, 'nh3': 7.22}, 'dt': 1606636800}, {'main': {'aqi': 5}, 'components': {'co': 427.25, 'no': 1.05, 'no2': 8.48, 'o3': 138.76, 'so2': 30.04, 'pm2_5': 67.77, 'pm10': 73.15, 'nh3': 6.9}, 'dt': 1606640400}, {'main': {'aqi': 5}, 'components': {'co': 640.87, 'no': 2.1, 'no2': 19.36, 'o3': 127.32, 'so2': 33.85, 'pm2_5': 78.94, 'pm10': 85.94, 'nh3': 11.02}, 'dt': 1606644000}, {'main': {'aqi': 5}, 'components': {'co': 988.01, 'no': 3.05, 'no2': 38.73, 'o3': 98.71, 'so2': 36.72, 'pm2_5': 95.02, 'pm10': 105.22, 'nh3': 17.23}, 'dt': 1606647600}, {'main': {'aqi': 5}, 'components': {'co': 1308.44, 'no': 1.57, 'no2': 61.69, 'o3': 60.08, 'so2': 37.67, 'pm2_5': 105.98, 'pm10': 119.67, 'nh3': 22.04}, 'dt': 1606651200}, {'main': {'aqi': 5}, 'components': {'co': 1455.31, 'no': 0.03, 'no2': 69.23, 'o3': 34.33, 'so2': 36.24, 'pm2_5': 110.66, 'pm10': 127.96, 'nh3': 25.59}, 'dt': 1606654800}, {'main': {'aqi': 5}, 'components': {'co': 1428.6, 'no': 0, 'no2': 57.58, 'o3': 35.05, 'so2': 32.9, 'pm2_5': 110.82, 'pm10': 129.98, 'nh3': 26.85}, 'dt': 1606658400}, {'main': {'aqi': 5}, 'components': {'co': 1268.39, 'no': 0, 'no2': 42.84, 'o3': 44.35, 'so2': 29.33, 'pm2_5': 106.55, 'pm10': 125.25, 'nh3': 25.59}, 'dt': 1606662000}, {'main': {'aqi': 5}, 'components': {'co': 1041.41, 'no': 0, 'no2': 29.13, 'o3': 55.08, 'so2': 23.84, 'pm2_5': 96.76, 'pm10': 114.06, 'nh3': 22.55}, 'dt': 1606665600}, {'main': {'aqi': 5}, 'components': {'co': 921.25, 'no': 0, 'no2': 23.65, 'o3': 57.94, 'so2': 20.27, 'pm2_5': 91.61, 'pm10': 107.75, 'nh3': 20.77}, 'dt': 1606669200}, {'main': {'aqi': 5}, 'components': {'co': 774.38, 'no': 0, 'no2': 19.88, 'o3': 59.37, 'so2': 16.21, 'pm2_5': 84.01, 'pm10': 98.39, 'nh3': 17.73}, 'dt': 1606672800}, {'main': {'aqi': 5}, 'components': {'co': 647.54, 'no': 0, 'no2': 16.62, 'o3': 60.8, 'so2': 13.47, 'pm2_5': 76.59, 'pm10': 88.17, 'nh3': 15.07}, 'dt': 1606676400}, {'main': {'aqi': 5}, 'components': {'co': 620.84, 'no': 0, 'no2': 14.91, 'o3': 59.37, 'so2': 14.19, 'pm2_5': 74.52, 'pm10': 84.11, 'nh3': 14.95}, 'dt': 1606680000}, {'main': {'aqi': 5}, 'components': {'co': 587.46, 'no': 0, 'no2': 12.85, 'o3': 58.65, 'so2': 13.71, 'pm2_5': 71.3, 'pm10': 79.5, 'nh3': 14.69}, 'dt': 1606683600}, {'main': {'aqi': 5}, 'components': {'co': 567.44, 'no': 0, 'no2': 12, 'o3': 56.51, 'so2': 13.71, 'pm2_5': 66.68, 'pm10': 74.01, 'nh3': 14.95}, 'dt': 1606687200}, {'main': {'aqi': 5}, 'components': {'co': 547.41, 'no': 0, 'no2': 11.65, 'o3': 56.51, 'so2': 14.19, 'pm2_5': 61.18, 'pm10': 67.88, 'nh3': 14.82}, 'dt': 1606690800}, {'main': {'aqi': 5}, 'components': {'co': 547.41, 'no': 0, 'no2': 12.17, 'o3': 58.65, 'so2': 15.5, 'pm2_5': 57.48, 'pm10': 63.72, 'nh3': 14.57}, 'dt': 1606694400}, {'main': {'aqi': 5}, 'components': {'co': 600.82, 'no': 0, 'no2': 14.57, 'o3': 57.22, 'so2': 17.41, 'pm2_5': 59.71, 'pm10': 66.36, 'nh3': 15.45}, 'dt': 1606698000}, {'main': {'aqi': 5}, 'components': {'co': 767.71, 'no': 0.01, 'no2': 22.62, 'o3': 44.7, 'so2': 21.46, 'pm2_5': 69.3, 'pm10': 78.1, 'nh3': 18.75}, 'dt': 1606701600}, {'main': {'aqi': 5}, 'components': {'co': 881.2, 'no': 1.22, 'no2': 28.45, 'o3': 35.05, 'so2': 25.27, 'pm2_5': 75.93, 'pm10': 87.07, 'nh3': 20.52}, 'dt': 1606705200}, {'main': {'aqi': 5}, 'components': {'co': 881.2, 'no': 4.36, 'no2': 23.99, 'o3': 42.2, 'so2': 26.7, 'pm2_5': 76.53, 'pm10': 89.06, 'nh3': 20.27}, 'dt': 1606708800}, {'main': {'aqi': 5}, 'components': {'co': 854.49, 'no': 5.2, 'no2': 21.42, 'o3': 59.37, 'so2': 30.04, 'pm2_5': 77.12, 'pm10': 90.12, 'nh3': 19.76}, 'dt': 1606712400}, {'main': {'aqi': 5}, 'components': {'co': 814.44, 'no': 4.47, 'no2': 20.91, 'o3': 85.12, 'so2': 35.76, 'pm2_5': 79.69, 'pm10': 92, 'nh3': 19}, 'dt': 1606716000}, {'main': {'aqi': 5}, 'components': {'co': 547.41, 'no': 2.71, 'no2': 15.94, 'o3': 114.44, 'so2': 42.92, 'pm2_5': 66.16, 'pm10': 73.32, 'nh3': 10.39}, 'dt': 1606719600}, {'main': {'aqi': 5}, 'components': {'co': 520.71, 'no': 2.38, 'no2': 16.28, 'o3': 130.18, 'so2': 47.68, 'pm2_5': 65.96, 'pm10': 72.13, 'nh3': 8.36}, 'dt': 1606723200}, {'main': {'aqi': 5}, 'components': {'co': 527.38, 'no': 2.15, 'no2': 18.17, 'o3': 143.05, 'so2': 54.36, 'pm2_5': 69.91, 'pm10': 76.08, 'nh3': 8.11}, 'dt': 1606726800}, {'main': {'aqi': 5}, 'components': {'co': 988.01, 'no': 4.58, 'no2': 43.87, 'o3': 127.32, 'so2': 70.57, 'pm2_5': 95.66, 'pm10': 105.02, 'nh3': 16.21}, 'dt': 1606730400}, {'main': {'aqi': 5}, 'components': {'co': 1815.8, 'no': 8.27, 'no2': 91.85, 'o3': 80.11, 'so2': 88.69, 'pm2_5': 137.08, 'pm10': 152.5, 'nh3': 28.37}, 'dt': 1606734000}, {'main': {'aqi': 5}, 'components': {'co': 2590.18, 'no': 12.41, 'no2': 141.2, 'o3': 20.39, 'so2': 97.28, 'pm2_5': 169.51, 'pm10': 190.75, 'nh3': 37.49}, 'dt': 1606737600}, {'main': {'aqi': 5}, 'components': {'co': 3364.56, 'no': 44.26, 'no2': 135.72, 'o3': 0.13, 'so2': 94.41, 'pm2_5': 200.67, 'pm10': 230.99, 'nh3': 47.62}, 'dt': 1606741200}, {'main': {'aqi': 5}, 'components': {'co': 4219.06, 'no': 79.57, 'no2': 109.67, 'o3': 0, 'so2': 89.65, 'pm2_5': 242.83, 'pm10': 284.79, 'nh3': 59.78}, 'dt': 1606744800}]}
{
         "coord": {
                  "lon": 72.5801,
                  "lat": 23.0215
         },
         "list": [
                  {
                           "main": {
                                    "aqi": 5
                           },
                           "components": {
                                    "co": 747.68,
                                    "no": 0,
                                    "no2": 21.59,
                                    "o3": 97.28,
                                    "so2": 23.84,
                                    "pm2_5": 70.46,
                                    "pm10": 81.04,
                                    "nh3": 14.82
                           },
                           "dt": 1606489200
                  },
                  {
                           "main": {
                                    "aqi": 5
                           },
                           "components": {
                                    "co": 734.33,
                                    "no": 0,
                                    "no2": 18.17,
                                    "o3": 100.14,
                                    "so2": 21.22,
                                    "pm2_5": 72.29,
                                    "pm10": 82.97,
                                    "nh3": 14.57
                           },
                           "dt": 1606492800
                  },
                  {
                           "main": {
                                    "aqi": 5
                           },
                           "components": {
                                    "co": 707.63,
                                    "no": 0,
                                    "no2": 15.42,
                                    "o3": 105.86,
                                    "so2": 19.31,
                                    "pm2_5": 77.1,
                                    "pm10": 87.09,
                                    "nh3": 13.3
                           },
                           "dt": 1606496400
                  },
                  {
                           "main": {
                                    "aqi": 5
                           },
                           "components": {
                                    "co": 640.87,
                                    "no": 0,
                                    "no2": 12.51,
                                    "o3": 110.15,
                                    "so2": 17.88,
                                    "pm2_5": 77.92,
                                    "pm10": 86.42,
                                    "nh3": 11.02
                           },
                           "dt": 1606500000
                  },
                  {
                           "main": {
                                    "aqi": 5
                           },
                           "components": {
                                    "co": 560.76,
                                    "no": 0,
                                    "no2": 9.68,
                                    "o3": 113.01,
                                    "so2": 17.17,
                                    "pm2_5": 73.69,
                                    "pm10": 80.47,
                                    "nh3": 9.12
                           },
                           "dt": 1606503600
                  },
                  {
                           "main": {
                                    "aqi": 5
                           },
                           "components": {
                                    "co": 520.71,
                                    "no": 0,
                                    "no2": 7.37,
                                    "o3": 113.01,
                                    "so2": 15.14,
                                    "pm2_5": 69.33,
                                    "pm10": 75.08,
                                    "nh3": 8.87
                           },
                           "dt": 1606507200
                  },
                  {
                           "main": {
                                    "aqi": 5
                           },
                           "components": {
                                    "co": 494,
                                    "no": 0,
                                    "no2": 6.68,
                                    "o3": 110.15,
                                    "so2": 14.31,
                                    "pm2_5": 65.34,
                                    "pm10": 70.52,
                                    "nh3": 9.12
                           },
                           "dt": 1606510800
                  },
                  {
                           "main": {
                                    "aqi": 5
                           },
                           "components": {
                                    "co": 487.33,
                                    "no": 0,
                                    "no2": 6.77,
                                    "o3": 105.86,
                                    "so2": 13.83,
                                    "pm2_5": 61.91,
                                    "pm10": 66.67,
                                    "nh3": 9.63
                           },
                           "dt": 1606514400
                  },
                  {
                           "main": {
                                    "aqi": 5
                           },
                           "components": {
                                    "co": 480.65,
                                    "no": 0,
                                    "no2": 6.86,
                                    "o3": 103,
                                    "so2": 13.35,
                                    "pm2_5": 58.87,
                                    "pm10": 63.33,
                                    "nh3": 9.88
                           },
                           "dt": 1606518000
                  },
                  {
                           "main": {
                                    "aqi": 5
                           },
                           "components": {
                                    "co": 487.33,
                                    "no": 0,
                                    "no2": 7.28,
                                    "o3": 98.71,
                                    "so2": 13.23,
                                    "pm2_5": 57.97,
                                    "pm10": 62.2,
                                    "nh3": 10.13
                           },
                           "dt": 1606521600
                  },
                  {
                           "main": {
                                    "aqi": 5
                           },
                           "components": {
                                    "co": 520.71,
                                    "no": 0,
                                    "no2": 8.91,
                                    "o3": 94.41,
                                    "so2": 13.71,
                                    "pm2_5": 58.74,
                                    "pm10": 63.26,
                                    "nh3": 10.77
                           },
                           "dt": 1606525200
                  },
                  {
                           "main": {
                                    "aqi": 5
                           },
                           "components": {
                                    "co": 594.14,
                                    "no": 0,
                                    "no2": 12.85,
                                    "o3": 87.26,
                                    "so2": 16.21,
                                    "pm2_5": 61.64,
                                    "pm10": 67.22,
                                    "nh3": 11.78

In [53]:
import requests,json
api_key="9e087baa4cae558ff2c7416885d00a12"
request_url=f"""http://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={long}&appid={api_key}"""
response=requests.get(request_url)
coordinates=response.json()
print(coordinates)
print(json.dumps(coordinates,indent=9,ensure_ascii=False))

{'cod': '200', 'message': 0, 'cnt': 40, 'list': [{'dt': 1780120800, 'main': {'temp': 305.73, 'feels_like': 308.35, 'temp_min': 305.73, 'temp_max': 310.8, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1001, 'humidity': 49, 'temp_kf': -5.07}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 51}, 'wind': {'speed': 6.68, 'deg': 233, 'gust': 7.79}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 06:00:00'}, {'dt': 1780131600, 'main': {'temp': 311.1, 'feels_like': 313.57, 'temp_min': 311.1, 'temp_max': 315.05, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 998, 'humidity': 33, 'temp_kf': -3.95}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 25}, 'wind': {'speed': 6.7, 'deg': 240, 'gust': 7.25}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 09:00:00'}, {'dt': 1780142400, 'main': {'temp': 315.05, 'feels_like': 315.75, 'temp_min': 315.05, 'temp_max': 315.05, 'pressure': 1001, 'sea_level': 1001, 'grnd_level': 995, 'humidity': 21, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 7.12, 'deg': 243, 'gust': 7.97}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 12:00:00'}, {'dt': 1780153200, 'main': {'temp': 308.71, 'feels_like': 311.43, 'temp_min': 308.71, 'temp_max': 308.71, 'pressure': 1003, 'sea_level': 1003, 'grnd_level': 998, 'humidity': 40, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 4.38, 'deg': 290, 'gust': 8.35}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-30 15:00:00'}, {'dt': 1780164000, 'main': {'temp': 305.29, 'feels_like': 309.08, 'temp_min': 305.29, 'temp_max': 305.29, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 55, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 4.71, 'deg': 265, 'gust': 8.49}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-30 18:00:00'}, {'dt': 1780174800, 'main': {'temp': 303.57, 'feels_like': 307.25, 'temp_min': 303.57, 'temp_max': 303.57, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1000, 'humidity': 62, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.06, 'deg': 226, 'gust': 6.93}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-30 21:00:00'}, {'dt': 1780185600, 'main': {'temp': 302.39, 'feels_like': 305.83, 'temp_min': 302.39, 'temp_max': 302.39, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 67, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 18}, 'wind': {'speed': 4.14, 'deg': 222, 'gust': 5.98}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 00:00:00'}, {'dt': 1780196400, 'main': {'temp': 304.64, 'feels_like': 308.01, 'temp_min': 304.64, 'temp_max': 304.64, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1003, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 11}, 'wind': {'speed': 5.61, 'deg': 213, 'gust': 6.54}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 03:00:00'}, {'dt': 1780207200, 'main': {'temp': 310.04, 'feels_like': 312.29, 'temp_min': 310.04, 'temp_max': 310.04, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 35, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 6}, 'wind': {'speed': 5.48, 'deg': 225, 'gust': 5.9}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 06:00:00'}, {'dt': 1780218000, 'main': {'temp': 314.1, 'feels_like': 315.44, 'temp_min': 314.1, 'temp_max': 314.1, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 999, 'humidity': 24, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 4.45, 'deg': 244, 'gust': 4.85}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 09:00:00'}, {'dt': 1780228800, 'main': {'temp': 314.33, 'feels_like': 315.41, 'temp_min': 314.33, 'temp_max': 314.33, 'pressure': 1002, 'sea_level': 1002, 'grnd_level': 997, 'humidity': 23, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 6.96, 'deg': 228, 'gust': 5.91}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 12:00:00'}, {'dt': 1780239600, 'main': {'temp': 306.65, 'feels_like': 310.16, 'temp_min': 306.65, 'temp_max': 306.65, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 999, 'humidity': 49, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 2.31, 'deg': 194, 'gust': 3.35}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 15:00:00'}, {'dt': 1780250400, 'main': {'temp': 306.02, 'feels_like': 308.63, 'temp_min': 306.02, 'temp_max': 306.02, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 48, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 13}, 'wind': {'speed': 2.13, 'deg': 325, 'gust': 3.63}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 18:00:00'}, {'dt': 1780261200, 'main': {'temp': 304.42, 'feels_like': 308.32, 'temp_min': 304.42, 'temp_max': 304.42, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 59, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 96}, 'wind': {'speed': 2.5, 'deg': 261, 'gust': 2.82}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 21:00:00'}, {'dt': 1780272000, 'main': {'temp': 303.27, 'feels_like': 306.85, 'temp_min': 303.27, 'temp_max': 303.27, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 63, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 85}, 'wind': {'speed': 4.91, 'deg': 244, 'gust': 6.41}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-01 00:00:00'}, {'dt': 1780282800, 'main': {'temp': 305.02, 'feels_like': 308.26, 'temp_min': 305.02, 'temp_max': 305.02, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1004, 'humidity': 54, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 55}, 'wind': {'speed': 4.47, 'deg': 225, 'gust': 5.62}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 03:00:00'}, {'dt': 1780293600, 'main': {'temp': 310.56, 'feels_like': 312.91, 'temp_min': 310.56, 'temp_max': 310.56, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1002, 'humidity': 34, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 36}, 'wind': {'speed': 5.17, 'deg': 231, 'gust': 6.16}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 06:00:00'}, {'dt': 1780304400, 'main': {'temp': 314.6, 'feels_like': 315.04, 'temp_min': 314.6, 'temp_max': 314.6, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 21, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 27}, 'wind': {'speed': 5.3, 'deg': 245, 'gust': 5.7}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 09:00:00'}, {'dt': 1780315200, 'main': {'temp': 314.46, 'feels_like': 315.63, 'temp_min': 314.46, 'temp_max': 314.46, 'pressure': 1003, 'sea_level': 1003, 'grnd_level': 998, 'humidity': 23, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 14}, 'wind': {'speed': 6.88, 'deg': 263, 'gust': 6.47}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 12:00:00'}, {'dt': 1780326000, 'main': {'temp': 309.07, 'feels_like': 310.54, 'temp_min': 309.07, 'temp_max': 309.07, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 35, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 3.25, 'deg': 243, 'gust': 5.75}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-01 15:00:00'}, {'dt': 1780336800, 'main': {'temp': 305.79, 'feels_like': 309.28, 'temp_min': 305.79, 'temp_max': 305.79, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 52, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 2.34, 'deg': 216, 'gust': 4.63}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-01 18:00:00'}, {'dt': 1780347600, 'main': {'temp': 303.75, 'feels_like': 308.12, 'temp_min': 303.75, 'temp_max': 303.75, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 3.66, 'deg': 293, 'gust': 6.32}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-01 21:00:00'}, {'dt': 1780358400, 'main': {'temp': 303.42, 'feels_like': 306.72, 'temp_min': 303.42, 'temp_max': 303.42, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 61, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 13}, 'wind': {'speed': 4.35, 'deg': 235, 'gust': 5.74}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-02 00:00:00'}, {'dt': 1780369200, 'main': {'temp': 304.5, 'feels_like': 308.23, 'temp_min': 304.5, 'temp_max': 304.5, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1003, 'humidity': 58, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 58}, 'wind': {'speed': 4.8, 'deg': 222, 'gust': 5.69}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-02 03:00:00'}, {'dt': 1780380000, 'main': {'temp': 309.66, 'feels_like': 312.6, 'temp_min': 309.66, 'temp_max': 309.66, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1001, 'humidity': 38, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 62}, 'wind': {'speed': 4.88, 'deg': 207, 'gust': 5.78}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-02 06:00:00'}, {'dt': 1780390800, 'main': {'temp': 313.64, 'feels_like': 315.06, 'temp_min': 313.64, 'temp_max': 313.64, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 999, 'humidity': 25, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 5}, 'wind': {'speed': 5.01, 'deg': 236, 'gust': 5.07}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-02 09:00:00'}, {'dt': 1780401600, 'main': {'temp': 313.55, 'feels_like': 314.91, 'temp_min': 313.55, 'temp_max': 313.55, 'pressure': 1002, 'sea_level': 1002, 'grnd_level': 996, 'humidity': 25, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 4}, 'wind': {'speed': 6.37, 'deg': 217, 'gust': 6.18}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-02 12:00:00'}, {'dt': 1780412400, 'main': {'temp': 306.76, 'feels_like': 310.39, 'temp_min': 306.76, 'temp_max': 306.76, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 998, 'humidity': 49, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 2}, 'wind': {'speed': 5.52, 'deg': 181, 'gust': 6.82}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-02 15:00:00'}, {'dt': 1780423200, 'main': {'temp': 304.47, 'feels_like': 308.95, 'temp_min': 304.47, 'temp_max': 304.47, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 61, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 33}, 'wind': {'speed': 4.19, 'deg': 153, 'gust': 6.11}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-02 18:00:00'}, {'dt': 1780434000, 'main': {'temp': 304.5, 'feels_like': 308.75, 'temp_min': 304.5, 'temp_max': 304.5, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 999, 'humidity': 60, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 54}, 'wind': {'speed': 3.25, 'deg': 303, 'gust': 4.55}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-02 21:00:00'}, {'dt': 1780444800, 'main': {'temp': 303.61, 'feels_like': 307.33, 'temp_min': 303.61, 'temp_max': 303.61, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 62, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 56}, 'wind': {'speed': 3.23, 'deg': 243, 'gust': 4.62}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-03 00:00:00'}, {'dt': 1780455600, 'main': {'temp': 305.3, 'feels_like': 309.1, 'temp_min': 305.3, 'temp_max': 305.3, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1000, 'humidity': 55, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 98}, 'wind': {'speed': 5.18, 'deg': 219, 'gust': 6.31}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-03 03:00:00'}, {'dt': 1780466400, 'main': {'temp': 310.66, 'feels_like': 313.85, 'temp_min': 310.66, 'temp_max': 310.66, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 999, 'humidity': 36, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 78}, 'wind': {'speed': 4.76, 'deg': 213, 'gust': 5.22}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-03 06:00:00'}, {'dt': 1780477200, 'main': {'temp': 314.45, 'feels_like': 316.93, 'temp_min': 314.45, 'temp_max': 314.45, 'pressure': 1001, 'sea_level': 1001, 'grnd_level': 996, 'humidity': 26, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 7}, 'wind': {'speed': 4.98, 'deg': 204, 'gust': 4.98}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-03 09:00:00'}, {'dt': 1780488000, 'main': {'temp': 312.47, 'feels_like': 315.4, 'temp_min': 312.47, 'temp_max': 312.47, 'pressure': 1000, 'sea_level': 1000, 'grnd_level': 995, 'humidity': 31, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 44}, 'wind': {'speed': 7.11, 'deg': 176, 'gust': 6.33}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-03 12:00:00'}, {'dt': 1780498800, 'main': {'temp': 305.83, 'feels_like': 309.94, 'temp_min': 305.83, 'temp_max': 305.83, 'pressure': 1002, 'sea_level': 1002, 'grnd_level': 997, 'humidity': 54, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 79}, 'wind': {'speed': 8, 'deg': 172, 'gust': 13.32}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-03 15:00:00'}, {'dt': 1780509600, 'main': {'temp': 307.55, 'feels_like': 311.4, 'temp_min': 307.55, 'temp_max': 307.55, 'pressure': 1002, 'sea_level': 1002, 'grnd_level': 997, 'humidity': 47, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 46}, 'wind': {'speed': 5.52, 'deg': 192, 'gust': 8.15}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-03 18:00:00'}, {'dt': 1780520400, 'main': {'temp': 305.01, 'feels_like': 308.5, 'temp_min': 305.01, 'temp_max': 305.01, 'pressure': 1003, 'sea_level': 1003, 'grnd_level': 998, 'humidity': 55, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 26}, 'wind': {'speed': 4.83, 'deg': 269, 'gust': 6.86}, 'visibility': 10000, 'pop': 0.99, 'rain': {'3h': 1.17}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-03 21:00:00'}, {'dt': 1780531200, 'main': {'temp': 304.23, 'feels_like': 307.2, 'temp_min': 304.23, 'temp_max': 304.23, 'pressure': 1003, 'sea_level': 1003, 'grnd_level': 998, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 51}, 'wind': {'speed': 3.63, 'deg': 211, 'gust': 5.44}, 'visibility': 10000, 'pop': 0.87, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-04 00:00:00'}, {'dt': 1780542000, 'main': {'temp': 306.15, 'feels_like': 308.88, 'temp_min': 306.15, 'temp_max': 306.15, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 999, 'humidity': 48, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 4}, 'wind': {'speed': 4.96, 'deg': 203, 'gust': 5.78}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-04 03:00:00'}], 'city': {'id': 1279233, 'name': 'Ahmedabad', 'coord': {'lat': 23.0215, 'lon': 72.5801}, 'country': 'IN', 'population': 3719710, 'timezone': 19800, 'sunrise': 1780100664, 'sunset': 1780149017}}
{
         "cod": "200",
         "message": 0,
         "cnt": 40,
         "list": [
                  {
                           "dt": 1780120800,
                           "main": {
                                    "temp": 305.73,
                                    "feels_like": 308.35,
                                    "temp_min": 305.73,
                                    "temp_max": 310.8,
                                    "pressure": 1007,
                                    "sea_level": 1007,
                                    "grnd_level": 1001,
                                    "humidity": 49,
                                    "temp_kf": -5.07
                           },
                           "weather": [
                                    {
                                             "id": 803,
                                             "main": "Clouds",
                                             "description": "broken clouds",
                                             "icon": "04d"
                                    }
                           ],
                           "clouds": {
                                    "all": 51
                           },
                           "wind": {
                                    "speed": 6.68,
                                    "deg": 233,
                                    "gust": 7.79
                           },
                           "visibility": 10000,
                           "pop": 0,
                           "sys": {
                                    "pod": "d"
                           },
                           "dt_txt": "2026-05-30 06:00:00"
                  },
                  {
                           "dt": 1780131600,
                           "main": {
                                    "temp": 311.1,
                                    "feels_like": 313.57,
                                    "temp_min": 311.1,
                                    "temp_max": 315.05,

In [54]:
import pandas as pd
D={'date_time':[],'temp':[],'feels_like':[],'temp_min':[],'temp_max':[],'pressure':[],'sea_level':[],'grnd_level':[],'humidity':[],'temp_kf':[]}
for i in coordinates['list']:
    D['date_time'].append(i['dt'])
    D['temp'].append(i['main']['temp'])
    D['feels_like'].append(i['main']['feels_like'])
    D['temp_min'].append(i['main']['temp_min'])
    D['temp_max'].append(i['main']['temp_max'])
    D['pressure'].append(i['main']['pressure'])
    D['sea_level'].append(i['main']['sea_level'])
    D['grnd_level'].append(i['main']['grnd_level'])
    D['humidity'].append(i['main']['humidity'])
    D['temp_kf'].append(i['main']['temp_kf'])
df=pd.DataFrame(D)
df

,date_time,temp,feels_like,temp_min,temp_max,pressure,sea_level,grnd_level,humidity,temp_kf
0,1780120800,305.73,308.35,305.73,310.80,1007,1007,1001,49,-5.07
1,1780131600,311.10,313.57,311.10,315.05,1005,1005,998,33,-3.95
2,1780142400,315.05,315.75,315.05,315.05,1001,1001,995,21,0.00
3,1780153200,308.71,311.43,308.71,308.71,1003,1003,998,40,0.00
4,1780164000,305.29,309.08,305.29,305.29,1005,1005,1000,55,0.00
5,1780174800,303.57,307.25,303.57,303.57,1006,1006,1000,62,0.00
6,1780185600,302.39,305.83,302.39,302.39,1006,1006,1001,67,0.00
7,1780196400,304.64,308.01,304.64,304.64,1008,1008,1003,56,0.00
8,1780207200,310.04,312.29,310.04,310.04,1007,1007,1002,35,0.00
9,1780218000,314.10,315.44,314.10,314.10,1004,1004,999,24,0.00
10,1780228800,314.33,315.41,314.33,314.33,1002,1002,997,23,0.00
11,1780239600,306.65,310.16,306.65,306.65,1005,1005,999,49,0.00
12,1780250400,306.02,308.63,306.02,306.02,1007,1007,1002,48,0.00
13,1780261200,304.42,308.32,304.42,304.42,1006,1006,1001,59,0.00
14,1780272000,303.27,306.85,303.27,303.27,1007,1007,1002,63,0.00
15,1780282800,305.02,308.26,305.02,305.02,1009,1009,1004,54,0.00
16,1780293600,310.56,312.91,310.56,310.56,1008,1008,1002,34,0.00
17,1780304400,314.60,315.04,314.60,314.60,1005,1005,1000,21,0.00
18,1780315200,314.46,315.63,314.46,314.46,1003,1003,998,23,0.00
19,1780326000,309.07,310.54,309.07,309.07,1005,1005,1000,35,0.00
20,1780336800,305.79,309.28,305.79,305.79,1007,1007,1002,52,0.00
21,1780347600,303.75,308.12,303.75,303.75,1006,1006,1001,64,0.00
22,1780358400,303.42,306.72,303.42,303.42,1007,1007,1002,61,0.00
23,1780369200,304.50,308.23,304.50,304.50,1008,1008,1003,58,0.00
24,1780380000,309.66,312.60,309.66,309.66,1007,1007,1001,38,0.00
25,1780390800,313.64,315.06,313.64,313.64,1004,1004,999,25,0.00
26,1780401600,313.55,314.91,313.55,313.55,1002,1002,996,25,0.00
27,1780412400,306.76,310.39,306.76,306.76,1004,1004,998,49,0.00
28,1780423200,304.47,308.95,304.47,304.47,1005,1005,1000,61,0.00
29,1780434000,304.50,308.75,304.50,304.50,1005,1005,999,60,0.00
30,1780444800,303.61,307.33,303.61,303.61,1005,1005,1000,62,0.00
31,1780455600,305.30,309.10,305.30,305.30,1006,1006,1000,55,0.00
32,1780466400,310.66,313.85,310.66,310.66,1005,1005,999,36,0.00
33,1780477200,314.45,316.93,314.45,314.45,1001,1001,996,26,0.00
34,1780488000,312.47,315.40,312.47,312.47,1000,1000,995,31,0.00
35,1780498800,305.83,309.94,305.83,305.83,1002,1002,997,54,0.00
36,1780509600,307.55,311.40,307.55,307.55,1002,1002,997,47,0.00
37,1780520400,305.01,308.50,305.01,305.01,1003,1003,998,55,0.00
38,1780531200,304.23,307.20,304.23,304.23,1003,1003,998,56,0.00
39,1780542000,306.15,308.88,306.15,306.15,1004,1004,999,48,0.00

In [55]:
# pressure<1005 humidity>60
df.loc[df['pressure']<1005]
df.loc[df['humidity']>60]

,date_time,temp,feels_like,temp_min,temp_max,pressure,sea_level,grnd_level,humidity,temp_kf
5,1780174800,303.57,307.25,303.57,303.57,1006,1006,1000,62,0.0
6,1780185600,302.39,305.83,302.39,302.39,1006,1006,1001,67,0.0
14,1780272000,303.27,306.85,303.27,303.27,1007,1007,1002,63,0.0
21,1780347600,303.75,308.12,303.75,303.75,1006,1006,1001,64,0.0
22,1780358400,303.42,306.72,303.42,303.42,1007,1007,1002,61,0.0
28,1780423200,304.47,308.95,304.47,304.47,1005,1005,1000,61,0.0
30,1780444800,303.61,307.33,303.61,303.61,1005,1005,1000,62,0.0

# Rest API

In [56]:
#Tokens (Authorization)
import requests
url="https://jsonplaceholder.typicode.com/posts"
token='my_secret_token'
h={'Authorization':f"Bearer {token}"}
response=requests.get(url,headers=h)
print(response.status_code)

200

In [57]:
response.headers

{'Date': 'Sat, 30 May 2026 03:22:23 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Cache-Control': 'max-age=43200', 'Content-Encoding': 'gzip', 'Etag': 'W/"6b80-Ybsq/K6GwwqrYkAsFxqDXGC7DoM"', 'Expires': '-1', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Pragma': 'no-cache', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=Je529wjJUbzjGCEDcWLDEWNei3j5WnkL6UMxENZw1Fw%3D\\u0026sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d\\u0026ts=1780104571"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=Je529wjJUbzjGCEDcWLDEWNei3j5WnkL6UMxENZw1Fw%3D&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&ts=1780104571"', 'Server': 'cloudflare', 'Vary': 'Origin, Accept-Encoding', 'Via': '2.0 heroku-router', 'X-Content-Type-Options': 'nosniff', 'X-Powered-By': 'Express', 'X-Ratelimit-Limit': '1000', 'X-Ratelimit-Remaining': '999', 'X-Ratelimit-Reset': '1780104628', 'Age': '6772', 'Cf-Cache-Status': 'HIT', 'CF-RAY': 'a03a9d3988eeb618-MRS', 'alt-svc': 'h3=":443"; ma=86400'}

In [58]:
#Pagination
import requests
url='https://jsonplaceholder.typicode.com/posts'
p={'_page':1,'_limit':5}
response=requests.get(url,params=p)
data=response.json()
print('posts from page:',p['_page'])
for post in data:
    print(post['id'],post['title'])

posts from page: 1
1 sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2 qui est esse
3 ea molestias quasi exercitationem repellat qui ipsa sit aut
4 eum et est occaecati
5 nesciunt quas odio

In [ ]:
# Pagination
import requests
url = "https://jsonplaceholder.typicode.com/posts"
p={"_page":2,"_limit":5}
response=requests.get(url, params=p)
data=response.json()
print("Posts from page:",p['_page'])
for post in data:
    print(post["id"], post["title"])

In [ ]:
# Pagination
import requests
url = "https://jsonplaceholder.typicode.com/posts"
p={"_page":3,"_limit":5}
response=requests.get(url, params=p)
data=response.json()
print("Posts from page:",p['_page'])
for post in data:
    print(post["id"], post["title"])

# CRUD : create=>read=>update=>delete

In [59]:
import requests
new_post={'title':'Learning Requests',
          'body':'This is tutorial content',
          'userId':1}
response=requests.post('https://jsonplaceholder.typicode.com/posts',json=new_post)
print(response.status_code)
print(response.json())
#201=created successfully

201
{'title': 'Learning Requests', 'body': 'This is tutorial content', 'userId': 1, 'id': 101}

In [60]:
#send put request
import requests
new_post={'id':1,
          'title':'updated title',
          'body':'updated body',
          'userId':1}
response=requests.put('https://jsonplaceholder.typicode.com/posts/1',json=new_post)
print(response.status_code)
print(response.json())
#201=created successfully

200
{'id': 1, 'title': 'updated title', 'body': 'updated body', 'userId': 1}

In [61]:
#patch data
patch_data={'title':'Patched title'}
response=requests.patch('https://jsonplaceholder.typicode.com/posts/1',json=patch_data)
print(response.status_code)
print(response.json())
#201=created successfully

200
{'userId': 1, 'id': 1, 'title': 'Patched title', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [62]:
#delete data
response=requests.delete('https://jsonplaceholder.typicode.com/posts/1')
print(response.status_code)

200

# Download image using binary contant

In [63]:
image_url='https://picsum.photos/500'
response=requests.get(image_url)
f=open('random_image.jpg','wb')
f.write(response.content)
f.close()
print('image downloaded')

image downloaded

# save json data to file

In [64]:
#convert python object into JSON string
person={'name':'bob','age':30}
with open('demo.json','w') as f:
    json.dump(person,f)
print('JSON file saved')

JSON file saved

In [65]:
with open('demo.json','r') as f:
    re=f.read()
    python_data=json.loads(re)
print(re)
print(type(python_data))

{"name": "bob", "age": 30}
<class 'dict'>

# Convert api response to Dataframe

In [63]:
import requests
import pandas as pd
response=requests.get('https://jsonplaceholder.typicode.com/posts')
posts=response.json()
df=pd.DataFrame(posts)
df.to_csv()
df.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [67]:
import requests

response = requests.get("https://jsonplaceholder.typicode.com/users")

users = response.json()

# print(users)

# Access first user's data
print(users[1]["name"])
print(users[1]["email"])
print(users[1]["address"]["city"])

Ervin Howell
Shanna@melissa.tv
Wisokyburgh